// Study notes ("Understand this verse") — distress cluster, part B:
// afraid, anxious, overwhelmed. Same structure as distress-a.cjs.
module.exports = {
  'Psalm 27:1': {
    story: 'David faced armies, assassins, and years of living as a hunted man. This psalm opens with the question he had learned to ask every fear: if the Lord is my light and my salvation — then whom, exactly, should I be afraid of?',
    meaning: 'Light drives out the darkness where fear breeds; salvation means rescue is already decided; "strength of my life" means your inner supports are His responsibility. The two questions are rhetorical: no one on earth outranks your Protector.',
    you: 'Name your fear, then put it next to God — that is what this verse trains you to do. Fear shrinks or grows depending on what you compare it to. Compared to the Lord, whom shall you fear?',
    prayer: 'Lord, You are my light, my salvation, my strength. I put today\'s fear next to You — and I watch it shrink. Amen.',
  },
  '2 Timothy 1:7': {
    story: 'Paul wrote this from a Roman death-row cell to Timothy, his timid young protégé who was tempted to shrink back from a dangerous calling. His argument: check where the fear is coming from — because it is not from God.',
    meaning: '"Spirit of fear" — a cowering, servile dread — is not God\'s gift; He never issued it. What He gave instead is power (ability to act), love (fear\'s opposite motivation), and a sound mind — self-controlled, clear thinking.',
    you: 'When panic speaks, you can literally answer: "This was not sent by my Father." Then take inventory of what He *did* send you: power, love, and a clear mind — enough for the thing in front of you.',
    prayer: 'Father, I return the fear — it is not from You. Fill me instead with Your power, Your love, and a sound mind. Amen.',
  },
  'Psalm 56:3': {
    story: 'David wrote this as a prisoner of the Philistines in Gath — enemy territory, no allies, real danger. The verse he produced there is only ten words long, and it is one of the most honest sentences in the Bible.',
    meaning: '"What time I am afraid" — David does not claim fearlessness; he assumes fear will come. The verse is a plan, not a boast: *when* fear arrives, *then* I will trust. Trust is the decision made inside the fear.',
    you: 'Faith is not the absence of fear — it is what you do with it. You can be scared and trusting in the same moment; that combination is not weakness, it is exactly what this verse describes.',
    prayer: 'Lord, I am afraid — and this is me, in the fear, choosing to trust You. Hold me steady. Amen.',
  },
  '1 John 4:18': {
    story: 'John, the disciple Jesus loved, was an old man when he wrote this letter. After a lifetime of walking with God he had discovered what finally evicts fear — and it is not courage. It is being perfectly loved.',
    meaning: '"Perfect love casteth out fear" — fear and love compete for the same room in your heart, and mature love wins. The fear in view is dread of punishment; when you know God fully loves you, dread has nothing left to feed on.',
    you: 'The cure for your fear is not becoming braver — it is becoming more convinced you are loved. Every inch of your heart that truly believes God loves you is an inch fear has to vacate.',
    prayer: 'Father, make Your love so real to me that fear runs out of room. I receive Your love — the whole of it. Amen.',
  },
  'Psalm 34:4': {
    story: 'David had just escaped Gath by pretending to be insane — a low, desperate trick born of terror. Looking back, he did not boast of his cleverness. He testified to something else: "I sought the Lord... he delivered me from all my fears."',
    meaning: 'Notice what God delivered David from: not just his enemies but his *fears* — the inner terror itself. Seeking the Lord is the action; being freed from fear, not only from danger, is the result.',
    you: 'God does not only change your circumstances; He can un-knot the dread inside you while circumstances stay the same. Seek Him about the fear itself — that is a prayer He loves to answer.',
    prayer: 'Lord, I seek You now — not just about my problem, but about my fear of it. Deliver me from the fear itself. Amen.',
  },
  'Isaiah 43:1-2': {
    story: 'God spoke these words to Israel on the far side of judgment, when they felt disowned and expendable. His answer reads like adoption papers: I created you, I redeemed you, I have called you by name — you are mine.',
    meaning: '"When thou passest through the waters" — not *if* but *when*: floods and fires come. The promise is not exemption but company and limits: with you in the water, and the flame "shall not kindle upon thee" — hard times without destruction.',
    you: 'You are not anonymous in your crisis. The God who calls you by name walks into the river beside you. This trouble can press you, but it has no permission to consume you.',
    prayer: 'Redeemer, You called me by name and said "thou art mine." Walk with me through this water — it will not overflow me. Amen.',
  },
  'Psalm 91:1-2': {
    story: 'This psalm — beloved by soldiers, travelers, and the sick for three thousand years — opens with a picture from the desert: the difference between wandering exposed under the sun and living inside a shelter.',
    meaning: '"He that dwelleth" — not visits, dwells. The secret place is a life habitually close to God, and its result is abiding "under the shadow of the Almighty." A shadow means He is that close — between you and the heat.',
    you: 'Shelter is real, but you must move in. Make God your habit — your first call, your daily refuge — and fear meets you differently, because it has to come through Him to reach you.',
    prayer: 'Most High, I move in today — You are my refuge and my fortress, my God. In You I put my trust. Amen.',
  },
  'Proverbs 3:25-26': {
    story: 'Solomon, the wisest of kings, taught his son about a specific kind of fear: the dread of sudden disaster — the phone call, the collapse, the ambush you never saw coming.',
    meaning: '"Be not afraid of sudden fear" — you are not required to live braced for catastrophe. Why? "The Lord shall be thy confidence" — your security is not your foresight or preparations, but a Person who is never surprised.',
    you: 'Anxiety rehearses disasters that have not happened. This proverb releases you from sentry duty: nothing can happen to you suddenly that is sudden to God. Let Him be the one who watches the horizon.',
    prayer: 'Lord, I resign from bracing for disaster. Nothing surprises You, and You are my confidence. Keep my foot from being taken. Amen.',
  },
  'Psalm 118:6': {
    story: 'This psalm was sung by pilgrims walking up to Jerusalem, and Jesus likely sang it with His disciples the night before the cross. Its logic steadied them: with the Lord on my side, what exactly can people do to me?',
    meaning: '"The Lord is on my side" — the strongest ally in existence has taken your case. "What can man do unto me?" is not naive — people can do painful things — but nothing outside God\'s reach, and nothing final.',
    you: 'So much fear is fear of people — their anger, rejection, opinions, power. Say this verse slowly when facing them: the Person on your side outweighs every person against you.',
    prayer: 'Lord, You are on my side — I will not fear. What people think or do cannot undo what You have decided for me. Amen.',
  },
  'Isaiah 41:13': {
    story: 'Through Isaiah, God kept repeating one message to His terrified people. Here He compresses it into a single image any child understands: a strong hand reaching down and closing around a smaller, shaking one.',
    meaning: '"I the Lord thy God will hold thy right hand" — God does not shout encouragement from a distance; He takes hold. And while holding, He speaks: "Fear not; I will help thee." Grip first, then words.',
    you: 'A child crossing a dangerous road is not asked to be brave — just to hold the hand. That is your assignment today: not manufactured courage, but a held hand and a listening ear.',
    prayer: 'Father, take my right hand — I am the small, shaking one. Say to me again, "Fear not, I will help thee." Amen.',
  },
  'Philippians 4:6-7': {
    story: 'Paul wrote "be careful for nothing" — be anxious about nothing — while chained in a Roman prison awaiting a verdict that could mean execution. This is not advice from a comfortable life; it is a prisoner\'s tested formula.',
    meaning: 'The exchange works like this: anxiety goes to God as prayer with thanksgiving; peace comes back — a peace that "passeth all understanding," meaning it does not make sense given your situation. It garrisons your heart like a military guard.',
    you: 'The verse gives worry one destination: everything, by prayer, with thanks, made known to God. Try it literally — tell Him each specific worry, thank Him for one thing each time, and let His unexplainable peace stand guard.',
    prayer: 'Father, here is everything I am anxious about — I hand it over with thanks. Let Your peace, which makes no sense, guard my heart and mind in Christ. Amen.',
  },
  '1 Peter 5:7': {
    story: 'Peter — the disciple who sank in the waves and cracked under pressure in a courtyard — wrote this to believers scattered under persecution. He had personally learned where anxiety must be taken.',
    meaning: '"Casting all your care upon him" is the same throwing word used for flinging a coat over a donkey. Every care, thrown — because of the reason given: "he careth for you." Your worries matter to Him because *you* matter to Him.',
    you: 'Anxiety is carrying alone what God offered to carry with you. The permission slip is the second half: He cares — about the exam, the bill, the diagnosis, the child. Nothing you carry is too small for His concern.',
    prayer: 'Lord, I throw the whole load onto You — every care, named one by one. Thank You that You genuinely care for me. Amen.',
  },
  'Matthew 6:25-26': {
    story: 'On the hillside, Jesus pointed at birds flying overhead — creatures with no barns, no savings, no plans — and asked His listeners to observe who was keeping them all alive.',
    meaning: '"Behold the fowls of the air" — Jesus commands observation: your heavenly Father feeds them. Then the argument: "Are ye not much better than they?" If God sustains sparrows, His children are not going to slip His mind.',
    you: 'Every bird you see today is a sermon with wings: cared for, without anxiety. You are worth more than many sparrows — the Father who has never missed feeding them is not going to start forgetting with you.',
    prayer: 'Father, You feed the birds who cannot store a thing. I am Your child — I trust You for what I need today. Amen.',
  },
  'Matthew 6:34': {
    story: 'Jesus closed His teaching on worry with startling practicality. He divided time into days and made a rule about it: tomorrow is not your assignment. It has not arrived, and you have not received grace for it yet.',
    meaning: '"Take therefore no thought for the morrow" — do not carry tomorrow today. "Sufficient unto the day is the evil thereof" — each day contains exactly enough trouble, and exactly enough grace, for itself. Borrowing tomorrow\'s doubles the load and halves the strength.',
    you: 'Most anxiety lives in tomorrow — a place you cannot act, fix, or pray from. Come back to today: what is actually in front of you now? That, and only that, is what today\'s grace covers.',
    prayer: 'Lord, I hand tomorrow back to You — it is Yours, not mine. Give me grace for today only, and I will meet You again in the morning. Amen.',
  },
  'John 14:27': {
    story: 'Dying men write wills. Hours from the cross, Jesus dictated His: "Peace I leave with you, my peace I give unto you." The only earthly possession He bequeathed His friends was the thing the world cannot manufacture.',
    meaning: 'The world gives peace by fixing circumstances — fragile, temporary. Jesus gives *His own* peace — the composure He carried through storms, trials, and crucifixion. "Not as the world giveth": His version survives conditions that destroy the world\'s.',
    you: 'You inherited this. Peace, His peace, is legally yours as a believer — which is why He can command: "Let not your heart be troubled." Stop treating peace as a mood and start claiming it as a bequest.',
    prayer: 'Jesus, I receive the peace You willed to me — Your own peace. Quiet my troubled heart; take the fear. Amen.',
  },
  'Isaiah 26:3': {
    story: 'Isaiah lived through the terror of the Assyrian war machine swallowing nations. In the middle of that era he wrote down the secret of the people who stayed sane: it mattered where their minds were "stayed."',
    meaning: '"Perfect peace" is literally "shalom, shalom" — peace doubled, complete wellness. The condition: a mind "stayed" — propped, leaned, fixed — on God. Peace follows attention. What the mind rests on, the heart absorbs.',
    you: 'Your mind is always leaning on something — the news, the what-ifs, or the Lord. Anxiety is often just attention pointed at the wrong object. Redirect the lean: think about who He is, and shalom-shalom follows.',
    prayer: 'Lord, I fix my mind on You — Your power, Your promises, Your care. Keep me in perfect peace as I lean here. Amen.',
  },
  'Psalm 94:19': {
    story: 'The psalmist was living under corrupt rulers and open injustice, with plenty to be anxious about. He describes an inner courtroom: a "multitude of thoughts within me" — a crowd of anxieties all talking at once.',
    meaning: '"In the multitude of my thoughts within me thy comforts delight my soul" — God\'s comforts do not wait for the crowd of thoughts to leave. They walk into the noisy room and begin delighting the soul right there.',
    you: 'You do not have to win the war in your head before God can comfort you. Invite His comfort into the middle of the racing thoughts — His voice does not need silence to be heard.',
    prayer: 'Father, my mind is a crowd today. Walk into the noise with Your comforts, and delight my soul in the middle of it. Amen.',
  },
  'Matthew 11:28-29': {
    story: 'Jesus invited the weary to take His "yoke" — the wooden crossbeam joining two oxen. Farmers paired a young ox with a seasoned one who bore the weight and set the pace. The picture is walking in harness beside Someone stronger.',
    meaning: '"Take my yoke... and learn of me; for I am meek and lowly in heart" — Jesus is a gentle master, and His yoke is "easy," meaning well-fitted. Rest comes not from leaving all work, but from pulling alongside Him at His pace.',
    you: 'Much exhaustion is self-inflicted pace. Yoked to Jesus, you go where He goes, at His speed, carrying His share — and you "find rest unto your souls," the deep kind. Are you pulling alone, or in harness?',
    prayer: 'Gentle Jesus, I take Your yoke. Set the pace, carry the weight, teach me as we walk — and give my soul rest. Amen.',
  },
  'Proverbs 12:25': {
    story: 'This proverb is ancient emotional wisdom in one sentence — thousands of years before psychology named it, Scripture described what anxiety does inside a person, and what a single good word can do about it.',
    meaning: '"Heaviness in the heart of man maketh it stoop" — anxiety physically bends a person under invisible weight. "But a good word maketh it glad" — one right word, spoken in, can lift what the weight pressed down.',
    you: 'Two applications: receive a good word — open Scripture daily and let God speak one in; and be a good word — someone near you is stooping under a hidden weight your encouragement could lift today.',
    prayer: 'Lord, speak Your good word into my heavy heart today — and make me a speaker of good words to someone else. Amen.',
  },
  'Psalm 46:1-2': {
    story: 'This psalm — the one that inspired "A Mighty Fortress Is Our God" — imagines the worst case scenario the ancient mind could conceive: earth removed, mountains dumped into the sea. Even then, it insists, we will not fear.',
    meaning: '"A very present help in trouble" — the Hebrew suggests help that is *found*, proven, immediately at hand. Not a distant God who must be summoned, but a refuge already standing when the earthquake starts.',
    you: 'The psalm does not say trouble will not come — it says when everything shakes, one thing does not. Your refuge is not the stability of your circumstances but the stability of your God.',
    prayer: 'God, my refuge and strength, things are shaking. You are very present — closer than the trouble. I will not fear. Amen.',
  },
  'Colossians 3:15': {
    story: 'Writing to believers pulled in every direction by false teachings and pressures, Paul used a sports word: let peace "rule" — act as umpire, the official who watches the play and makes the call.',
    meaning: '"Let the peace of God rule in your hearts" — when you face a decision or a swirl of thoughts, God\'s peace umpires: its presence signals "safe," its absence signals "hold." And note the last three words of the verse: "and be ye thankful" — gratitude keeps the umpire audible.',
    you: 'You are not meant to referee your inner life alone. Practice asking: does this thought, choice, or path carry His peace? Let peace make the call — and thank Him out loud, because thankful hearts hear the umpire best.',
    prayer: 'Lord, let Your peace be the umpire of my heart today — calling safe what is Yours, and out what is not. Make me thankful. Amen.',
  },
  'Psalm 61:2': {
    story: 'David prayed this "from the end of the earth" — far from home, spirit fainting, likely on the run again. His prayer contains one of the most honest admissions in the Psalms: the safe place is higher than I can climb.',
    meaning: '"When my heart is overwhelmed: lead me to the rock that is higher than I" — David does not ask for a map to the rock; he asks to be *led* there, like someone too weak to travel alone. The refuge exceeds his reach; the leading is God\'s job.',
    you: 'Overwhelm means the situation is bigger than you — this verse agrees, and is not embarrassed. You do not need to be equal to the rock; you only need to be led. Cry from wherever "the end of the earth" is for you.',
    prayer: 'Lord, my heart is overwhelmed — the way out is higher than I can climb. Take my hand and lead me to the Rock. Amen.',
  },
  '2 Corinthians 12:9': {
    story: 'Paul begged God three times to remove a tormenting "thorn in the flesh." God said no — and explained the no with a sentence Paul treasured for the rest of his life: my strength is made perfect in weakness.',
    meaning: '"My grace is sufficient for thee" — enough, exactly enough, resupplied daily. "Strength made perfect in weakness" means God\'s power shows up best where yours runs out; your limits are His display windows.',
    you: 'You keep apologising for your weakness; God plans to exhibit His power in it. The overwhelmed places you hide are the precise venues where His grace intends to be seen. Sufficiency is His problem, not yours.',
    prayer: 'Lord, Your grace is enough for me today — not my strength, Yours. Be strong exactly where I am weak. Amen.',
  },
  'Philippians 4:13': {
    story: 'A prisoner wrote this. In the previous breath Paul described knowing hunger and abundance, having everything and nothing — and claimed he had learned contentment in all of it. Then he named his secret.',
    meaning: '"I can do all things through Christ which strengtheneth me" — the "all things" in context are all *circumstances*: any situation God assigns, Paul could face, because Christ kept pouring strength in. It is a verse about endurance, even more than achievement.',
    you: 'This is not a slogan for winning trophies — it is oxygen for surviving seasons. Whatever today assigns you, the promise holds: Christ will strengthen you *for that*, as you go, from the inside.',
    prayer: 'Christ my strength, I cannot do this on my own — and I do not have to. Strengthen me for exactly what today holds. Amen.',
  },
  'Psalm 46:1': {
    story: 'Ancient cities survived sieges by their fortresses — thick walls people ran inside when the enemy appeared. This psalm hands that picture to every believer: God Himself is the wall you run into.',
    meaning: 'Three titles, each an anchor: refuge (where you hide), strength (what fills you when hiding is not enough), and "a very present help in trouble" — help that is already on the scene before you finish calling.',
    you: 'Notice you do not have to travel to this fortress; He is "very present" — nearer than the trouble itself. Run in: tell Him plainly, "You are my refuge right now," and stay until your pulse remembers it.',
    prayer: 'God, my refuge and strength, I run inside You now. You are already present in this trouble — closer than it is. Amen.',
  },
  'Isaiah 43:2': {
    story: 'God gave this promise to people headed into literal displacement — rivers to cross, empires to survive. Centuries earlier their ancestors had walked through the Red Sea and a furnace in Babylon had failed to burn three of them. God\'s record stood behind His words.',
    meaning: 'Waters, rivers, fire, flame — a rising scale of ordeals, each met with the same guarantee: through, not under. "They shall not overflow thee... neither shall the flame kindle upon thee." Trials have God-set limits.',
    you: 'The promise is passage: *through* the waters. The current is real and the heat is real — but so is the boundary God has drawn around them. This season will be something you came through, not something that swallowed you.',
    prayer: 'Lord, I am in deep water — but You are with me in it, and it will not overflow me. Bring me through. Amen.',
  },
  'Psalm 142:3': {
    story: 'The title of this psalm preserves its address: a cave. David hid in caves from Saul with his life priced. In the dark he admitted his spirit was overwhelmed — and then said something remarkable about being known.',
    meaning: '"When my spirit was overwhelmed within me, then thou knewest my path" — when David could no longer see the way, God still could. Overwhelm blinds the traveler, not the Guide. The path exists even when you cannot perceive it.',
    you: 'Feeling lost is not being lost. Your inability to see three steps ahead has no effect on God\'s knowledge of the whole road. When your spirit says "there is no way through this," answer it: He knows my path.',
    prayer: 'Lord, I cannot see the way — but You know my path completely. Lead me one step at a time out of this cave. Amen.',
  },
  'Psalm 121:1-2': {
    story: 'Pilgrims sang this psalm climbing the dangerous hill roads to Jerusalem — bandits above, cliffs below. Looking up at those hills, they asked the traveler\'s question: where does my help come from? And answered it.',
    meaning: '"My help cometh from the Lord, which made heaven and earth" — the psalm connects your small journey to the biggest credential in existence: the Maker of everything. A Creator-sized Helper for footpath-sized troubles.',
    you: 'Look at what towers over you today — then finish the pilgrim\'s sentence: my help comes from the One who made heaven and earth. The mountains are big; their Maker is on your side.',
    prayer: 'Maker of heaven and earth, I lift my eyes to You. Be my help on this road — my keeper who never sleeps. Amen.',
  },
  'Isaiah 40:29': {
    story: 'Isaiah 40 begins "Comfort ye my people." Near its end comes this verse for the exhausted — set between a description of God who never faints and young men who do. The difference is who gets resupplied.',
    meaning: '"He giveth power to the faint" — God\'s specialty is not rewarding the strong but resourcing the finished. "To them that have no might he increaseth strength" — zero is not disqualification; it is the starting condition He works best with.',
    you: 'You do not need to bring strength to God — you need to bring your emptiness honestly. "No might" is exactly the account He deposits into. Come drained; leave supplied.',
    prayer: 'Lord, I am faint and my strength is gone — which makes me exactly who this promise is for. Give me power today. Amen.',
  },
  'Deuteronomy 33:27': {
    story: 'These are lines from Moses\' final blessing, spoken over Israel days before his death. After forty years of watching God carry a complaining, stumbling people through a wilderness, this was his summary of what held them.',
    meaning: '"The eternal God is thy refuge, and underneath are the everlasting arms" — underneath: beneath the lowest point you can fall to, arms are already waiting. Everlasting: they do not tire, age, or withdraw.',
    you: 'You are afraid of the bottom falling out. This verse tells you what is at the bottom: everlasting arms. However far you sink in this season, you will land on God — and He will not drop you.',
    prayer: 'Eternal God, my refuge — thank You that beneath my worst falling place are Your everlasting arms. I rest my weight on them. Amen.',
  },
};
