// Study notes ("Understand this verse") — distress cluster, part A:
// sad, grieving, lonely, depressed. Original plain-language commentary written
// for beginners: story = the human situation behind the verse, meaning = the
// verse in simple words, you = what it says to the reader today, prayer = a
// short prayer to make it personal. Keys must match curation references exactly.
module.exports = {
  'Psalm 34:18': {
    story: 'David wrote this psalm after one of the most humiliating days of his life — running from King Saul, he pretended to be insane in front of a foreign king just to survive. He knew what a crushed heart feels like.',
    meaning: '"Nigh" is an old word for near. When your heart is broken, God does not step back in disgust — He moves closer. A "contrite spirit" simply means a spirit that has been crushed flat by life or by sorrow over sin.',
    you: 'You may feel that your sadness pushes everyone away, even God. This verse says the opposite: your broken heart is the very address God comes to. You do not have to clean yourself up before He will come near.',
    prayer: 'Father, my heart is heavy today. Thank You that You come close to me right now, exactly as I am. Stay near me. Amen.',
  },
  'Psalm 30:5': {
    story: 'David wrote this song for the dedication of his house, looking back on a season when he thought everything was lost — sickness, enemies, tears at night. Then morning came, and with it, joy he did not expect.',
    meaning: 'The picture is of a guest: weeping may "endure" — stay the night like a visitor — but it must leave in the morning. Pain is real, but in God\'s hands it is temporary. Joy is what lasts.',
    you: 'Whatever you are crying about tonight is not your permanent address. Night always feels endless at 3am — but morning is already on its way, because God has decided it.',
    prayer: 'Lord, this night feels long. Help me hold on until Your morning comes, and let me recognise the joy when it arrives. Amen.',
  },
  'Psalm 147:3': {
    story: 'This psalm was sung when the Israelites came home from exile in Babylon to rebuild Jerusalem — a city of broken walls and broken people. The same God who was rebuilding their walls was rebuilding their hearts.',
    meaning: 'To "bind up" is what a doctor does — cleaning a wound, wrapping it gently so it can heal. God is pictured not as a judge over the brokenhearted, but as a physician kneeling beside them.',
    you: 'A wound needs two things: someone who sees it and someone who tends it. God does both. He is not rushing your healing — He is wrapping it, layer by layer, with care.',
    prayer: 'Healer of hearts, I bring You my wounds — the ones nobody else sees. Bind them up gently, and teach me to let You. Amen.',
  },
  'Psalm 55:22': {
    story: 'David wrote this while being betrayed by a close friend — someone he had worshipped with. The pain of betrayal was crushing him, and this verse is what he learned to do with weight too heavy to carry.',
    meaning: '"Cast" is a throwing word — not gently placing, but heaving something off your shoulders onto someone stronger. A "burden" is whatever is crushing you. "Sustain" means He will hold you up so you do not collapse.',
    you: 'God is not asking you to manage your burden better. He is asking you to throw it — prayers do not need to be neat to count. What are you still carrying that He has offered to hold?',
    prayer: 'Lord, I have carried this long enough. Right now I throw it onto You — the whole weight of it. Hold me up today. Amen.',
  },
  'John 11:35': {
    story: 'Jesus arrived at the tomb of His friend Lazarus four days too late — on purpose. He knew He was about to raise him from the dead. And yet, standing with the weeping sisters Mary and Martha, Jesus wept too.',
    meaning: 'This is the shortest verse in the Bible, and one of the deepest. Jesus knew the story would end in resurrection — but He still cried. Knowing the ending does not make Him dismiss the pain of the middle.',
    you: 'God never says "stop crying, it will be fine." He sits down in your grief and weeps with you first. Your tears do not annoy Him; they move Him.',
    prayer: 'Jesus, thank You that You are not far from my tears — You have cried some of Your own. Sit with me in this. Amen.',
  },
  'Matthew 5:4': {
    story: 'On a hillside in Galilee, Jesus opened His most famous sermon with a list of surprising blessings. The crowd expected Him to bless the strong and successful. Instead, His second blessing went to people in mourning.',
    meaning: '"Blessed" means deeply well-off in God\'s eyes — not because mourning is good, but because mourners are the ones who will personally experience God\'s comfort. The promise is certain: they *shall* be comforted.',
    you: 'The world calls mourning weakness. Jesus calls it a doorway — the place where God\'s comfort finds you. You are not falling behind by grieving; you are exactly where the promise applies.',
    prayer: 'Lord Jesus, I am one of the mourners You blessed. I hold You to Your promise — comfort me the way only You can. Amen.',
  },
  'Psalm 42:11': {
    story: 'The writer of this psalm was far from Jerusalem, unable to worship at the temple, surrounded by people asking "Where is your God?" He felt forgotten — so he did something striking: he started talking to his own soul.',
    meaning: '"Cast down" means sunk low, like something pressed under water. "Disquieted" means churning and restless. The psalmist does not deny his depression — he interrogates it, then preaches to himself: hope in God. Praise will come again.',
    you: 'You can be honest about the darkness and still preach hope to your own heart in the same breath. Faith is not pretending you are fine; it is telling your soul where to look.',
    prayer: 'God, my soul is heavy and restless. Teach me to speak hope to myself the way this psalm does — You are my help. Amen.',
  },
  'Revelation 21:4': {
    story: 'John wrote Revelation as an old man exiled on a prison island, after watching his friends die for their faith. At the end of his vision, God showed him how the whole story finishes — with God Himself drying every eye.',
    meaning: 'Notice who does the wiping: not an angel, but God, personally, like a parent with a crying child. Death, sorrow, crying, pain — the verse lists them like enemies being escorted out, never to return.',
    you: 'Every tear you have ever cried is on a list of things God has promised to end. This world\'s pain has an expiry date. You are not walking toward darkness — you are walking toward the wiping of tears.',
    prayer: 'Father, when the pain feels endless, remind me of the ending You have already written. I am waiting for that day. Amen.',
  },
  '2 Corinthians 1:3-4': {
    story: 'Paul had just come through suffering in Asia so severe he "despaired even of life." Writing to the Corinthians afterwards, he did not hide it — he explained what his pain had produced: comfort he could now hand to others.',
    meaning: 'God is called "the Father of mercies and the God of all comfort" — comfort is not just something He gives; it is who He is. And His comfort is designed to flow through you, not just to you.',
    you: 'Nothing you are suffering will be wasted. The comfort God gives you in this valley is training — one day someone will sit in front of you with the same pain, and you will know exactly what they need.',
    prayer: 'God of all comfort, comfort me in this trouble — and when I am through it, make me a comfort to someone else. Amen.',
  },
  'Psalm 56:8': {
    story: 'David wrote this when he had been captured by his enemies in Gath — alone, afraid, and far from home. In that cell he pictured something tender: God keeping a record of every one of his wanderings and tears.',
    meaning: 'In David\'s time, travelers carried precious water in a bottle. David dares to believe God treats his tears like that — collected, counted, written in His book. Nothing about your sorrow is unnoticed or lost.',
    you: 'You may think nobody sees what this is costing you. God does — down to the individual tear. Sorrow that is seen and kept is sorrow that matters.',
    prayer: 'Lord, thank You that not one of my tears has fallen without You noticing. You keep count of what everyone else missed. Amen.',
  },
  'Psalm 126:5': {
    story: 'This psalm was sung by exiles returning to a ruined homeland. They had to plant seeds in devastated fields, weeping as they worked — yet believing harvest would come to those same fields.',
    meaning: 'The picture is a farmer crying while planting. Sowing in tears means faithfully doing what must be done even while it hurts. The promise is that the same field where you cried will be the field where you shout for joy.',
    you: 'Keep planting — keep praying, keep working, keep showing up — even in tears. In God\'s economy, tears water seeds. The harvest will grow precisely where you wept.',
    prayer: 'Father, I am sowing in tears right now. Help me believe the harvest is coming, and let me live to reap it with joy. Amen.',
  },
  'John 16:22': {
    story: 'Hours before His arrest, Jesus prepared His disciples for the worst night of their lives. He compared their coming grief to childbirth: real pain — but pain that ends in a joy nobody can undo.',
    meaning: 'Jesus does not deny that sorrow is coming; He promises what comes after: "I will see you again." The joy of the resurrection was a joy "no man taketh from you" — permanent, theft-proof joy.',
    you: 'Some sorrows in your life will end this same way — with seeing again, with restoration, with a joy that cannot be stolen back. Grief has an end date; the joy Jesus gives does not.',
    prayer: 'Jesus, in my sorrow, plant Your promise: joy is coming that no one can take from me. Help me hold on until then. Amen.',
  },
  'Isaiah 53:3': {
    story: 'Seven hundred years before the cross, Isaiah described a coming Servant of God — not a glittering king, but "a man of sorrows, acquainted with grief," rejected and avoided. Christians recognised the portrait: it is Jesus.',
    meaning: '"Acquainted with grief" means grief was not a stranger to Him — He knew it personally, by name. The Saviour of the world did not skip suffering; He majored in it.',
    you: 'Whatever sorrow you carry, you are not explaining it to someone who has only read about pain. Jesus was despised, rejected, and heartbroken. He understands you from the inside.',
    prayer: 'Man of sorrows, thank You that You know grief by name. Since You understand mine, I bring it to You without shame. Amen.',
  },
  'Psalm 23:4': {
    story: 'David spent his youth as a shepherd, leading sheep through dark ravines where predators waited. Writing his most beloved psalm, he remembered: the sheep were never in those valleys alone.',
    meaning: 'The "valley of the shadow of death" is any dark passage where death or loss casts its shadow. The verse never promises a detour around the valley — it promises company through it: "thou art with me."',
    you: 'Notice the psalm shifts here from talking *about* God ("He leadeth me") to talking *to* Him ("Thou art with me"). Valleys do that — they turn theory into conversation. He is walking this one with you.',
    prayer: 'Shepherd, I cannot see the end of this valley. But You are in it with me, and that is enough for the next step. Amen.',
  },
  'John 11:25-26': {
    story: 'Martha\'s brother had been dead four days when Jesus arrived. Her greeting was half faith, half accusation: "If you had been here…" Jesus answered with one of the greatest claims ever spoken beside a grave.',
    meaning: 'Jesus does not say He *brings* resurrection — He says He *is* it. Life is not a thing He hands out; it is who He is. For those who believe in Him, death becomes a doorway, not a wall.',
    you: 'If you have lost someone who trusted Jesus, this verse is His personal word to you at that graveside: they live. And His question to Martha is His question to you: "Believest thou this?"',
    prayer: 'Jesus, Resurrection and Life, hold my grief and my hope together. I believe — help my unbelief at the hard moments. Amen.',
  },
  '1 Thessalonians 4:13-14': {
    story: 'The new believers in Thessalonica were grieving — some of their loved ones had died before Jesus returned, and they feared those believers had missed everything. Paul wrote to correct the fear, not the grief.',
    meaning: 'Paul does not say "do not grieve." He says do not grieve "as others which have no hope." Christian grief is real grief — but it is grief with a horizon: those who died in Jesus will rise as surely as He did.',
    you: 'You are allowed to cry at the grave of a believer. Just know your tears fall on temporary ground. The separation is real, but it is not final — that is the difference hope makes.',
    prayer: 'Father, I grieve — but as one with hope. Thank You that goodbye in Christ always secretly means "see you later." Amen.',
  },
  'Psalm 73:26': {
    story: 'Asaph, a worship leader, wrote this after nearly losing his faith watching wicked people prosper while he suffered. He came out the other side with one unshakeable possession: God Himself.',
    meaning: '"My flesh and my heart faileth" — body and courage can both give out. "Portion" is an inheritance word: of everything a person could own, Asaph says God Himself is his share, and that share lasts forever.',
    you: 'Grief strips things away until you discover what cannot be taken. When strength, health, or even a loved one is gone, God remains — the strength of your heart, your portion forever.',
    prayer: 'God, when everything in me fails, be the strength of my heart. You are my portion — the one thing I cannot lose. Amen.',
  },
  'John 14:1-3': {
    story: 'The disciples were reeling — Jesus had just announced He was leaving and one of them was a traitor. Into that panic, Jesus spoke about His Father\'s house, where He was going ahead to prepare their rooms.',
    meaning: '"Mansions" simply means dwelling places, rooms. Heaven is described not as a hotel but a family home — and Jesus is personally preparing your place. "I will come again" is a promise, not a maybe.',
    you: 'A troubled heart calms down when it knows where the story ends: a prepared place, a returning Saviour, and being where He is. Whoever you have lost in Christ is not homeless — and neither are you.',
    prayer: 'Jesus, thank You for preparing a place with my name on it. Untrouble my heart with the certainty of Your return. Amen.',
  },
  'Romans 8:38-39': {
    story: 'Paul ends the greatest chapter he ever wrote with a list. He piles up every force that could possibly stand between a believer and God — death, life, angels, powers, height, depth — and cancels each one.',
    meaning: '"Persuaded" means Paul examined the evidence and settled it. Nothing on the list — and the list covers everything, including death itself — can separate you from the love of God in Christ Jesus.',
    you: 'Grief whispers that death has separated you from love. This verse answers: death cannot do that — not to you, and not to those who died in Christ. His love holds both of you still.',
    prayer: 'Father, persuade my heart of what Paul was persuaded of: nothing — not even death — can cut me off from Your love. Amen.',
  },
  'Psalm 116:15': {
    story: 'The writer of this psalm had come terrifyingly close to death — "the sorrows of death compassed me" — and been rescued. Reflecting on it, he learned how God regards the death of His faithful ones.',
    meaning: '"Precious in the sight of the Lord" — the death of one of God\'s saints is never cheap, random, or unnoticed to Him. It is a costly, weighty moment that He attends personally.',
    you: 'The person you lost did not slip away unseen. If they belonged to God, their final breath was precious to Him — He was watching, receiving, welcoming. Your loved one mattered to the very end, and beyond it.',
    prayer: 'Lord, thank You that the one I miss was precious to You in death as in life. Keep them, and comfort me. Amen.',
  },
  'Isaiah 25:8': {
    story: 'Isaiah, surrounded by nations at war and death on every side, was given a preview of the end of history: a mountain, a feast, and God doing something no king had ever done — swallowing up death itself.',
    meaning: 'Death is pictured as a devourer that swallows everyone — until God turns the tables and swallows *it*, "in victory," permanently. Then the Lord God personally wipes the tears from every face.',
    you: 'Death looks unbeatable from where you stand. But its own destruction is already scheduled. The enemy that took your loved one will itself be swallowed — and God will dry your face with His own hand.',
    prayer: 'God of victory, I look forward to the day You swallow death forever. Until then, wipe my tears as only You can. Amen.',
  },
  'Lamentations 3:31-32': {
    story: 'Lamentations was written in the smoking ruins of Jerusalem — the writer had watched his city burn and his people marched into exile. Yet in the exact centre of the book\'s despair, he plants these words.',
    meaning: '"The Lord will not cast off for ever" — grief has a limit set by God\'s character. Though He allows sorrow, He will have compassion "according to the multitude of his mercies" — His mercy outnumbers your griefs.',
    you: 'This feels permanent. It is not. The One who permitted this season has already set its boundary, and His compassion is on the way in quantities you cannot yet imagine.',
    prayer: 'Lord, this sorrow feels forever — but You say it is not. I wait for Your compassion, which outnumbers my tears. Amen.',
  },
  'Deuteronomy 31:6': {
    story: 'Moses was 120 years old, about to die, handing the nation to Joshua at the edge of the promised land. His farewell gift to a frightened people was this promise about who was actually going with them.',
    meaning: 'Two verbs anchor it: God will not "fail" you (loosen His grip) and will not "forsake" you (walk away). Courage is commanded only because company is guaranteed — He goes with you.',
    you: 'Loneliness says everyone eventually leaves. This verse names the exception: the Lord your God. People may have failed you or left you — He is constitutionally unable to do either.',
    prayer: 'God who goes with me, when I feel abandoned, remind me that You have never loosened Your grip on me. Amen.',
  },
  'Hebrews 13:5': {
    story: 'The writer of Hebrews was addressing believers who had lost property and status for their faith. His antidote for both greed and fear was one direct quotation from God: "I will never leave thee, nor forsake thee."',
    meaning: 'In the original language this promise stacks up negatives for emphasis — something like "I will never, never leave you; never, never, never forsake you." It is the strongest "never" grammar can build.',
    you: 'Read it slowly as God\'s own words to you, because that is what they are: "I will never leave *you*." Not when you fail, not when you doubt, not when everyone else has gone home. Never.',
    prayer: 'Father, write Your five-fold never on my lonely heart today: You will not leave me. You will not forsake me. Amen.',
  },
  'Psalm 68:6': {
    story: 'David composed this psalm celebrating God\'s march through history rescuing His people. Among the mighty images — armies scattered, mountains shaking — sits this tender line about what God does for lonely individuals.',
    meaning: '"God setteth the solitary in families" — He is a home-finder for the isolated. The God who commands galaxies spends His attention placing lonely people into belonging, and leading prisoners out into freedom.',
    you: 'Your isolation is not invisible to God, and it is not His plan for you. He is a placer-of-the-lonely — ask Him to set you in the family, friendship, or church community He has in mind.',
    prayer: 'Father of the lonely, You set the solitary in families. Lead me to the belonging You have prepared for me. Amen.',
  },
  'Psalm 25:16': {
    story: 'David — a king surrounded by servants and soldiers — wrote one of the loneliest sentences in the Bible. Position and crowds had not cured him: "I am desolate and afflicted," he told God plainly.',
    meaning: '"Turn thee unto me" — David asks for God\'s face to rotate toward him, like asking someone across the room to look at you. He does not dress up his loneliness; he presents it as the reason for mercy.',
    you: 'You can be surrounded and still desolate — God knows that. This verse is permission to pray the most honest prayer there is: "Look at me, Lord. I am lonely." That prayer has been in His book for 3,000 years.',
    prayer: 'Turn to me, Lord, and be gracious to me, for I am lonely and hurting. Let me feel Your face toward me today. Amen.',
  },
  'Matthew 28:20': {
    story: 'These are the final recorded words of Jesus on earth. On a mountain in Galilee, sending His friends out to reach the world, His last sentence was not an instruction — it was a promise of company.',
    meaning: '"Alway" translates a phrase meaning "all the days" — ordinary Mondays, dark days, days you fail. "Unto the end of the world" leaves no gap. His presence is continuous until history closes.',
    you: 'Whatever today is for you, it is one of "all the days" — which means He is in it. You have never had an un-accompanied day in your life since you came to Him, and you never will.',
    prayer: 'Jesus, You promised to be with me all the days. Make Your presence real to me on this one. Amen.',
  },
  'Psalm 139:7-10': {
    story: 'David wrote this psalm marveling that God knew him completely. He runs a thought experiment — sky, grave, the far side of the sea — trying to imagine one location outside God\'s presence. He fails.',
    meaning: '"Whither shall I flee from thy presence?" is a rhetorical question; the answer is nowhere. Even in the uttermost parts, "thy right hand shall hold me" — not just near me, but holding me.',
    you: 'You may feel you have drifted somewhere God\'s presence does not reach — too far, too dark, too low. According to this psalm, no such place exists. Even here, His hand holds you.',
    prayer: 'Lord, since there is nowhere I can go from Your Spirit, I stop running. Hold me with Your right hand, even here. Amen.',
  },
  'Psalm 27:10': {
    story: 'David knew rejection from every direction across his life — dismissed by his father at Samuel\'s visit, hunted by his king, betrayed by his son. Out of that he wrote a sentence for the abandoned.',
    meaning: '"When my father and my mother forsake me" names the deepest human abandonment possible — and answers it: "then the Lord will take me up," the way someone lifts and adopts an abandoned child.',
    you: 'If the people who were supposed to love you didn\'t — or couldn\'t, or left — this verse was written for exactly that wound. God\'s response to your abandonment is adoption.',
    prayer: 'Father, others let go of me, but You take me up. Be the parent, the family, the home that never fails me. Amen.',
  },
  'John 14:18': {
    story: 'Jesus was hours from leaving His disciples, and they knew it. Their teacher, protector, and friend was going — so He made them a promise using the most vulnerable word possible: orphans.',
    meaning: '"Comfortless" literally means "as orphans." Jesus promises His leaving is not abandonment: "I will come to you" — fulfilled by His resurrection and by sending the Holy Spirit to live in believers.',
    you: 'You are not on your own in the universe. If you belong to Jesus, His own Spirit lives with you and in you. Whatever you walk into today, you walk into it fathered, not orphaned.',
    prayer: 'Jesus, thank You that You did not leave me an orphan. Let Your Spirit make Your presence real in me today. Amen.',
  },
  'Isaiah 41:10': {
    story: 'God spoke these words through Isaiah to Israel facing exile among hostile empires — a tiny, terrified people. Notice how many times God says "I" — the entire verse is Him taking responsibility for them.',
    meaning: 'Five promises stack up: I am with thee; I am thy God; I will strengthen thee; I will help thee; I will uphold thee. "Uphold" pictures God\'s right hand under you, keeping you from going down.',
    you: 'Fear and loneliness both shrink when you count the "I will" statements aimed at you. You are not asked to be strong first — His strength arrives precisely where yours ends.',
    prayer: 'My God, You said "Fear thou not, for I am with thee." I take You at Your word today — strengthen, help, uphold me. Amen.',
  },
  'Psalm 73:23': {
    story: 'Asaph confessed that envy and bitterness had made him "as a beast" before God — senseless, sour, sliding. Yet looking back at his worst stretch he discovered something astonishing about it.',
    meaning: '"Nevertheless I am continually with thee: thou hast holden me by my right hand." Even while Asaph was bitter and barely believing, God never let go of his hand. The holding did not depend on Asaph\'s mood.',
    you: 'On the days you feel spiritually numb or far away, the truth is unchanged: you are continually with Him, and He is holding your hand — including right now, whether you can feel it or not.',
    prayer: 'Lord, even when my heart was sour, You never dropped my hand. Thank You for a grip that does not depend on my feelings. Amen.',
  },
  'Joshua 1:9': {
    story: 'Moses was dead, and Joshua — his assistant for forty years — suddenly had to lead two million people across a river into hostile territory. God\'s commissioning speech repeated one command three times: be courageous.',
    meaning: '"Have not I commanded thee?" — courage here is not a personality trait but an order, resting on one fact: "the Lord thy God is with thee whithersoever thou goest." Wherever you go — He is already committed to being there.',
    you: 'God does not ask if you feel brave; He supplies the reason to act brave: His presence travels with you. The next hard thing you must do, you will not do alone.',
    prayer: 'Lord, You command courage and You supply the company. I will take the next step, because You go with me. Amen.',
  },
  'Psalm 34:17': {
    story: 'David composed this psalm as an escaped fugitive who had just cried out to God from real danger — and been heard. He turned his rescue into a general promise for all the righteous who cry.',
    meaning: '"The righteous cry" — not polished prayers, just crying out. "The Lord heareth" — hearing, for God, includes acting: "delivereth them out of all their troubles." All, eventually, is His jurisdiction.',
    you: 'Your cry does not need vocabulary. If all you can produce today is a groan aimed at God, that qualifies — He hears, and hearing, He moves. No cry of yours has ever hit a closed ceiling.',
    prayer: 'Lord, hear my cry today — it is not eloquent, but it is real. Deliver me in Your time, out of all of this. Amen.',
  },
  'Psalm 40:1-2': {
    story: 'David describes an experience like being stuck in a pit of wet clay — the more you struggle, the deeper you sink. He could not climb out. What he could do was wait and cry — and God did the lifting.',
    meaning: '"I waited patiently" is literally "waiting, I waited" — long, aching waiting. Then four verbs belong to God: He inclined, heard, brought up, set my feet on rock. The rescue is entirely His work.',
    you: 'Depression can feel exactly like miry clay — every effort sinks you deeper. This psalm says your job in the pit is smaller than you think: cry and wait. The lifting is God\'s department, and He does it.',
    prayer: 'God of the pit-rescue, I am waiting and crying — that is all I have. Bring me up, set my feet on rock, steady my steps. Amen.',
  },
  '1 Kings 19:7-8': {
    story: 'Elijah had just won the greatest spiritual victory of his life — then one death threat sent him fleeing into the desert, where he prayed to die. God\'s response was not a rebuke. It was a nap and two meals.',
    meaning: 'The angel touched him twice: sleep, food, more sleep, more food — "because the journey is too great for thee." God treated Elijah\'s despair first as exhaustion, with tenderness instead of shame.',
    you: 'Sometimes the most spiritual thing you can do is sleep, eat, and let God be gentle with you. If God did not scold His burnt-out prophet, He is not scolding you. Rest is not failure; it is treatment.',
    prayer: 'Father, I am worn down past my strength. Feed me, rest me, and be as gentle with me as You were with Elijah. Amen.',
  },
  'Isaiah 40:31': {
    story: 'Isaiah wrote to exiles who believed God had forgotten them. He pointed at the night sky — the God who names every star does not faint — and made a promise to everyone whose strength had run out.',
    meaning: '"They that wait upon the Lord" — waiting means hoping, depending, staying oriented toward Him. "Renew" is literally "exchange": you trade your spent strength for His. Eagles\' wings, running, walking — grace for every pace.',
    you: 'Notice the order ends with walking. Some seasons you will soar, some you will run — and some days, not fainting while you walk is the miracle. His strength covers that day too.',
    prayer: 'Lord, my strength is finished. I wait on You now — exchange my emptiness for Your power, one day at a time. Amen.',
  },
  'Lamentations 3:22-23': {
    story: 'These verses were written by a man sitting in the ashes of everything — Jerusalem destroyed, the temple burned, his people deported. At rock bottom he noticed one thing that had survived: God\'s mercy, arriving fresh at sunrise.',
    meaning: '"It is of the Lord\'s mercies that we are not consumed" — the fact that you are still here is itself mercy. "New every morning" means compassion is re-supplied daily, never stale, never rationed from yesterday.',
    you: 'Yesterday\'s mercy was for yesterday. When you woke today, a fresh consignment was already waiting — measured for today\'s troubles exactly. You will never face a morning that His compassions have not already reached.',
    prayer: 'Faithful God, Your mercies are new this very morning. Help me live today on today\'s supply. Great is Your faithfulness. Amen.',
  },
  'Matthew 11:28': {
    story: 'Jesus looked at crowds crushed by religious rules and daily survival — "labouring and heavy laden" — and issued the most generous invitation ever given. Not "try harder." Simply: "Come unto me."',
    meaning: 'Every religion says "do." Jesus says "come." The invitation has one qualification — being tired and burdened — and one promise: "I will give you rest." Rest is a gift He gives, not a wage you earn.',
    you: 'You qualify for this invitation right now — weariness is the entrance ticket. Stop trying to fix yourself first. Come as you are, hand Him the load, and let Him do what He promised: give you rest.',
    prayer: 'Jesus, I am tired in a way sleep does not fix. I come to You now, burdens and all. Give me Your rest. Amen.',
  },
  'Psalm 3:3': {
    story: 'David wrote this psalm on the worst night of his life — fleeing Jerusalem barefoot and weeping because his own son Absalom had seized the throne and wanted him dead. Yet he slept that night. This verse is why.',
    meaning: 'Three titles: a shield around me (protection on every side), my glory (my worth when I have lost everything), and the lifter up of mine head (the hand under a chin that cannot rise on its own).',
    you: 'When shame or sorrow makes your head hang, God does not shout "look up!" from a distance. He comes close and lifts your head Himself — gently, like family. Let Him.',
    prayer: 'Lord, be my shield today, my worth when I feel worthless, and the gentle hand that lifts my head. Amen.',
  },
  '2 Corinthians 4:8-9': {
    story: 'Paul listed his real resume to the Corinthians: troubled, perplexed, persecuted, cast down. Beaten and shipwrecked more than anyone, he attached to each blow a stubborn "but not" — the margin where grace lives.',
    meaning: 'Troubled, *but not* distressed; perplexed, *but not* in despair; persecuted, *but not* forsaken; cast down, *but not* destroyed. Pressure is real, but for the believer it always stops short of destruction.',
    you: 'You may be pressed hard on every side right now — but you are not crushed. Knocked down is not knocked out. The "but not" written over Paul\'s life is written over yours.',
    prayer: 'God of the "but not," I am pressed and struck down — yet by Your grace not crushed, not destroyed. Keep me standing. Amen.',
  },
  'Psalm 27:13-14': {
    story: 'David wrote this psalm with armies and false witnesses against him. He admits in verse 13 what almost happened: "I had fainted, unless I had believed" — hope in God was the thread he survived by.',
    meaning: '"The goodness of the Lord in the land of the living" — David expected to see God\'s goodness *in this life*, not only after it. "Wait on the Lord" brackets the promise: courage grows in the waiting room.',
    you: 'Depression tells you the good is over. This verse insists there is goodness of God still ahead of you — in the land of the living, on this side of heaven. Believe that, and your heart can hold on.',
    prayer: 'Lord, keep me from fainting. I choose to believe I will yet see Your goodness in the land of the living. Amen.',
  },
  'John 16:33': {
    story: 'This is the last sentence Jesus spoke to His disciples before praying and walking to His arrest. He told them the truth twice: in Him, peace; in the world, tribulation. Then He said something outrageous for a man hours from a cross: "I have overcome the world."',
    meaning: 'Jesus does not promise escape from trouble — He guarantees trouble ("ye *shall* have tribulation") and then guarantees something bigger: His victory. "Be of good cheer" is only sane because the outcome is already decided.',
    you: 'Your trouble is real, but it is happening inside a war that has already been won. You are not fighting *for* victory today — you are fighting *from* it.',
    prayer: 'Overcoming Jesus, my trouble is real but so is Your victory. Give me peace in You and courage for today. Amen.',
  },
  'Psalm 143:7-8': {
    story: 'David prayed this from a dark place — an enemy had "smitten my life down to the ground" and his spirit was overwhelmed. His prayer is startlingly honest: answer quickly, Lord, before I go under completely.',
    meaning: '"Hear me speedily... my spirit faileth" — Scripture makes room for urgent, desperate prayer. Then the beautiful request: "Cause me to hear thy lovingkindness in the morning" — let Your love be the first voice I hear.',
    you: 'When you are at the end, you do not need long prayers — you need honest ones. Ask what David asked: that tomorrow morning, before the dread speaks, God\'s love gets the first word.',
    prayer: 'Lord, my spirit is failing — answer me soon. Tomorrow morning, let me hear Your lovingkindness before anything else. Amen.',
  },
};
