// Study notes — need cluster, part B: provision, wronged.
module.exports = {
  'Philippians 4:19': {
    story: 'The Philippians had given sacrificially to support Paul\'s ministry — out of their own poverty. His thank-you letter closes with a promise drawn not on his account, but on God\'s.',
    meaning: '"My God shall supply all your need according to his riches in glory by Christ Jesus" — the supply is measured "according to" His riches, not out of a small allowance from them. The budget behind the promise is the wealth of heaven.',
    you: 'Your needs are calculated against your income; God\'s supply is calculated against His riches in glory. Those are different mathematics. Bring Him the whole list — the funding source is not strained.',
    prayer: 'My God, You promised to supply all my need from riches in glory. I bring You today\'s needs and trust Your budget. Amen.',
  },
  'Matthew 6:31-33': {
    story: 'Jesus named the three anxieties that have kept humans awake in every century — what shall we eat, drink, wear — and offered a complete reorganisation of the worried life around one pursuit.',
    meaning: '"Your heavenly Father knoweth that ye have need of all these things" — your needs are already itemised in heaven. "Seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you" — put first things first, and second things are thrown in.',
    you: 'Worry auditions you for a role already filled — provider. Your part is different: seek His kingdom first, today, in your priorities and choices. The "adding" of everything else is His signed responsibility.',
    prayer: 'Father, You already know what I need. Today I seek Your kingdom first — and leave the adding to You. Amen.',
  },
  'Psalm 23:1': {
    story: 'David had been a shepherd — he knew exactly how much a sheep\'s welfare depends on who owns it. The most famous sentence in the Psalms is him realising which side of that arrangement he was on.',
    meaning: '"The Lord is my shepherd; I shall not want" — everything hangs on the little word "my." Because the Lord Himself shepherds him, lack is off the table: pasture, water, protection, direction — the shepherd\'s job, not the sheep\'s.',
    you: 'Sheep do not carry wallets or worry about next season — they follow closely and are provided for. Your assignment is nearness, not anxiety. Say it in first person until it settles: the Lord is *my* shepherd.',
    prayer: 'Lord, You are my shepherd — mine. I shall not want. Keep me close to You, and quiet the fear of lack. Amen.',
  },
  'Matthew 6:26': {
    story: 'Teaching on a Galilean hillside, Jesus gestured at the birds overhead — creatures with no agriculture, no storage, no payroll — and asked His listeners to draw the obvious conclusion about their own Father.',
    meaning: '"They sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?" — the argument runs from lesser to greater: if He feeds birds, He will not neglect children.',
    you: 'God has run a daily feeding operation for every bird on earth since creation without missing a morning. You are worth more than many sparrows — your provision is not where His record breaks.',
    prayer: 'Heavenly Father, You feed the birds every single day. I am Your child — I rest in the same faithfulness. Amen.',
  },
  'Psalm 37:25': {
    story: 'David wrote Psalm 37 explicitly as an old man — "I have been young, and now am old" — handing the next generation the conclusions of a lifetime of watching God deal with the righteous.',
    meaning: '"Yet have I not seen the righteous forsaken, nor his seed begging bread" — a lifetime\'s testimony: God\'s people go through hardship, but abandonment is not in the record. The witness of the old is evidence for the worried young.',
    you: 'Ask the oldest faithful believers you know whether God ever finally abandoned them. Their answer will match David\'s. You are not the case where His faithfulness fails.',
    prayer: 'Faithful God, generations testify that You never forsake the righteous. Write the same testimony across my life. Amen.',
  },
  'Luke 12:24': {
    story: 'Jesus pointed His disciples to ravens — unclean birds under Jewish law, the least deserving-looking creatures in the sky — and made them a lesson in the economics of God\'s care.',
    meaning: '"Consider the ravens: for they neither sow nor reap; which neither have storehouse nor barn; and God feedeth them: how much more are ye better than the fowls?" — even the unclean scavenger is on God\'s payroll. "How much more" — His children rank far above.',
    you: 'God feeds even the birds nobody blesses. Whatever you feel you deserve or do not deserve, provision in God\'s house was never merit-based. "How much more" covers you.',
    prayer: 'Lord, You feed the ravens without them earning it. How much more will You care for me — I trust that arithmetic. Amen.',
  },
  'Proverbs 3:9-10': {
    story: 'Solomon taught his son a counter-intuitive money principle drawn from Israel\'s harvest law: the first portion went to God — before bills, before storage, before certainty about the rest of the season.',
    meaning: '"Honour the Lord with thy substance, and with the firstfruits of all thine increase: so shall thy barns be filled with plenty" — giving God the first share is called honour, and honour opens the way for blessing on the remainder.',
    you: 'Giving first, when money is tight, feels reckless — that is exactly what makes it worship. Put God at the top line of your budget, not the leftovers line, and watch what He does with the rest.',
    prayer: 'Lord, I honour You with my firstfruits — the first share, not the scraps. The rest is in Your hands. Amen.',
  },
  'Malachi 3:10': {
    story: 'Israel was withholding tithes in lean times, effectively starving the temple. Through Malachi, God issued the only invitation in Scripture where He says: test me on this.',
    meaning: '"Bring ye all the tithes into the storehouse... and prove me now herewith, saith the Lord of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it" — a challenge with His own reputation as the stake.',
    you: 'God invites your scepticism — into an experiment. Faithful giving is the one area where He says "prove me." Take Him up on it and keep records; He intends to win.',
    prayer: 'Lord of hosts, I take Your challenge — I will bring the whole tithe and watch You keep Your word. Open the windows. Amen.',
  },
  '2 Corinthians 9:8': {
    story: 'Encouraging the Corinthians toward cheerful generosity, Paul stacked the word "all" into one sentence more densely than anywhere else in his letters — a verse practically overflowing on purpose.',
    meaning: '"God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work" — all grace, always, all sufficiency, all things: total coverage, aimed at making you a conduit, not a container.',
    you: 'God supplies you sufficiently so generosity stays possible — provision has a purpose beyond your bills. As you give, you position yourself midstream in the "all grace" current.',
    prayer: 'God of all grace, make me sufficient in all things — and make me generous, so Your supply flows through me. Amen.',
  },
  'Psalm 34:10': {
    story: 'David wrote this while hiding in a cave system, having lost his position, home, and safety. Even there, he drew a bold comparison between apex predators and people who seek God.',
    meaning: '"The young lions do lack, and suffer hunger: but they that seek the Lord shall not want any good thing" — even the strongest hunters go hungry some nights; seekers of the Lord have a different guarantee: no *good* thing withheld.',
    you: 'Note the word "good" — the promise filters, it does not spoil. What God withholds was not good for you; what is good for you, He will not withhold. Seek Him and trust the filter.',
    prayer: 'Lord, I seek You first. Withhold what would harm me, supply every good thing — I trust Your judgment between them. Amen.',
  },
  'Matthew 7:11': {
    story: 'Jesus closed His teaching on prayer with an argument every parent instantly understands — reasoning from flawed human fathers up to the perfect one.',
    meaning: '"If ye then, being evil, know how to give good gifts unto your children, how much more shall your Father which is in heaven give good things to them that ask him?" — even sinful parents do not hand their children stones for bread. God\'s giving exceeds the best father\'s by "how much more."',
    you: 'Measure your view of God against this: is the Father you pray to at least as kind as a decent human parent? He is infinitely kinder. Ask like a child who has never been given a stone.',
    prayer: 'Father in heaven, You give better than the best earthly father. I come asking, confident in Your "how much more." Amen.',
  },
  'Psalm 84:11': {
    story: 'The sons of Korah wrote this psalm about longing for God\'s house — a pilgrim song. Near its end sits a two-sided promise about what God is and what He therefore does.',
    meaning: '"The Lord God is a sun and shield: the Lord will give grace and glory: no good thing will he withhold from them that walk uprightly" — sun (light, warmth, life) and shield (protection); grace now, glory later; and the sweeping negative: no good thing withheld.',
    you: 'If it is truly good, and you are walking with Him, it is not being withheld — it is being timed. The gap between prayer and provision is scheduling, not stinginess.',
    prayer: 'Lord God, my sun and shield — give grace today and glory ahead. I trust that nothing good is being kept from me. Amen.',
  },
  '1 Peter 2:23': {
    story: 'Peter watched Jesus\'s trial from the courtyard — heard the insults, saw the injustice. Decades later he described what Jesus did with the abuse, and named the discipline behind the silence.',
    meaning: '"When he was reviled, reviled not again; when he suffered, he threatened not; but committed himself to him that judgeth righteously" — the secret of Jesus\'s restraint: continuous handover. Each insult was passed directly to the righteous Judge.',
    you: 'You do not have to answer every accusation or avenge every wound — you have somewhere to send them. Do what Jesus did with each fresh injury: commit it, immediately, to the Judge who gets everything right.',
    prayer: 'Righteous Judge, like Jesus I hand You each insult and injury as it lands. Judge rightly — and free me from the fight. Amen.',
  },
  'Matthew 5:44': {
    story: 'In a land occupied by Rome, where hatred of enemies felt like patriotism, Jesus issued the most revolutionary command of the Sermon on the Mount — and He would later obey it Himself, praying for His executioners.',
    meaning: '"Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you" — four active verbs, none of them feelings. Enemy-love is conduct: bless, do good, pray. Feelings follow behaviour.',
    you: 'Start with the easiest command: pray for them, by name, today. It is nearly impossible to keep hating someone you genuinely pray for — prayer is where enemy-love becomes possible.',
    prayer: 'Lord, You prayed for Your executioners. Give me grace to pray for [name] — bless them, and heal me as I do. Amen.',
  },
  'Romans 12:17-18': {
    story: 'Paul wrote this to Christians living in Nero\'s Rome — people with real enemies and no legal recourse. His instructions draw the boundaries of a believer\'s responsibility in conflict.',
    meaning: '"Recompense to no man evil for evil... If it be possible, as much as lieth in you, live peaceably with all men" — the phrase "as much as lieth in you" is realistic: you control only your side of every relationship. Own your side completely; release theirs.',
    you: 'Peace does not always depend on you — but your part always does. Ask: have I done everything that lies in me? If yes, you are free; their response is between them and God.',
    prayer: 'Lord, show me what lies in me to do for peace — and give me grace to do all of it, then release the rest to You. Amen.',
  },
  'Proverbs 20:22': {
    story: 'This proverb addresses the moment right after injury — when the heart drafts its plans for repayment. It interrupts the draft with a better offer.',
    meaning: '"Say not thou, I will recompense evil; but wait on the Lord, and he shall save thee" — the command targets the inner vow ("I will pay them back"). The alternative is active waiting on the Lord, who takes over both your defense and your vindication.',
    you: 'Revenge planning feels productive; it is only corrosive. Cancel the inner vow today — say instead, "I wait on the Lord." He saves; He settles; and He does both better than your plan.',
    prayer: 'Lord, I cancel my repayment plans. I wait on You — save me, vindicate me, and keep my heart clean while I wait. Amen.',
  },
  '1 Peter 3:9': {
    story: 'Writing to believers being slandered and mistreated for their faith, Peter taught them the family trade: responding to evil in a way that turns injury into inheritance.',
    meaning: '"Not rendering evil for evil, or railing for railing: but contrariwise blessing; knowing that ye are thereunto called, that ye should inherit a blessing" — the exchange rate of the kingdom: absorb evil, release blessing, receive blessing. It is your calling and your payout.',
    you: 'Every insult is a fork: reflect it or transform it. Blessing those who wound you is not weakness — it is trading in the currency of your inheritance.',
    prayer: 'Father, when evil comes at me today, help me send blessing back — and receive the blessing You attached to that calling. Amen.',
  },
  'Isaiah 54:17': {
    story: 'This promise closes a chapter addressed to storm-tossed, afflicted Israel — the "heritage of the servants of the Lord": a settled, inherited protection over God\'s people.',
    meaning: '"No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn" — weapons may be formed and tongues may rise, but their success is vetoed. This security is called an inheritance — yours by belonging, not by fighting.',
    you: 'The verse does not promise no weapons — it promises no prospering. Attacks launched at you have a ceiling set by God. Stand on your inheritance instead of your anxiety.',
    prayer: 'Lord, weapons have been formed and tongues have risen — but You said they shall not prosper. I claim my heritage. Amen.',
  },
  'Genesis 50:20': {
    story: 'Joseph\'s brothers sold him into slavery; he passed through pits, false accusation, and prison over twenty years — then stood before those same brothers as Egypt\'s saviour and delivered history\'s greatest reframe.',
    meaning: '"Ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people alive" — two intentions ran through the same events: theirs evil, God\'s good. God\'s meaning outran and overruled theirs.',
    you: 'Someone\'s evil against you is not the final author of your story. God writes with crooked pens. Give Him the full twenty years if needed — the day may come when you see what He meant it for.',
    prayer: 'Sovereign God, what they meant for evil, You can mean for good. Write Your better ending through my worst chapter. Amen.',
  },
  'Luke 6:27-28': {
    story: 'Jesus preached this to people living under occupation, taxation, and casual brutality — audiences with real, daily enemies. He gave them four escalating responses to hostility, each one active.',
    meaning: '"Love your enemies, do good to them which hate you, bless them that curse you, and pray for them which despitefully use you" — love as action, good as deeds, blessing as words, prayer as intercession. The victim becomes the initiator; the cycle breaks at your link.',
    you: 'Hatred keeps you chained to the person who hurt you. These four verbs are the bolt-cutters. Begin where you can — even a single grudging prayer for them starts the chain coming off.',
    prayer: 'Lord, I take up the four verbs against my bitterness: help me love, do good, bless, and pray — starting today. Amen.',
  },
  'Romans 12:21': {
    story: 'Paul ends his chapter on Christian living with a single-sentence battle doctrine — the summary of everything he said about enemies, revenge, and injury.',
    meaning: '"Be not overcome of evil, but overcome evil with good" — evil wins the moment it turns you into its mirror. It loses the moment goodness answers it. Every response you choose is territory gained by one side or the other.',
    you: 'The person who wronged you cannot make you bitter — only your response can. Refuse to be colonised: answer their evil with stubborn, creative good, and you have already won the exchange.',
    prayer: 'Lord, do not let evil recruit me through my wounds. Make me an overcomer — good answering evil until it yields. Amen.',
  },
  'Psalm 9:9': {
    story: 'David composed this psalm of praise after seeing justice done against his enemies. In the middle of the celebration he states what he has learned God reliably is for a whole class of people.',
    meaning: '"The Lord also will be a refuge for the oppressed, a refuge in times of trouble" — refuge here is literally a high tower, elevated above the flood and the fight. For the oppressed specifically — the wronged, the crushed — He keeps the tower open.',
    you: 'If you have been wronged and have no advocate, you qualify for this address. The tower is not for the strong who need nothing — it is expressly for the oppressed. Run in; the door is yours.',
    prayer: 'Lord, high tower of the oppressed, I run to You with my injustice. Shelter me, defend me, and hold me above the flood. Amen.',
  },
};
