// Study notes — seeking cluster, part C: worshipful, numb.
module.exports = {
  'Psalm 100:1-2': {
    story: 'Psalm 100 is titled "A Psalm of praise" — the only psalm to carry that exact heading. It was Israel\'s call to public, joyful worship, summoning everyone within earshot to come loudly and gladly.',
    meaning: '"Make a joyful noise unto the Lord, all ye lands. Serve the Lord with gladness: come before his presence with singing" — "joyful noise" does not require a good voice; it requires a glad heart. Worship here is loud, corporate, and cheerful — service done with gladness, not grim duty.',
    you: 'You do not need to be a singer to worship — you need a heart willing to make a joyful noise. God is not auditioning your voice; He is delighting in your gladness. Come to Him singing, however it sounds.',
    prayer: 'Lord, I make a joyful noise to You today. Serve alongside me as I serve You with gladness, and receive my song. Amen.',
  },
  'Psalm 95:1-2': {
    story: 'This psalm was likely sung as worshippers processed toward the temple. It opens with an urgent, communal summons — "come, let us" — inviting everyone to run toward God as toward a rescuer.',
    meaning: '"O come, let us sing unto the Lord: let us make a joyful noise to the rock of our salvation. Let us come before his presence with thanksgiving" — God is called "the rock of our salvation" — solid, saving, unmovable. Worship starts with thanksgiving and rises into song, aimed at the One who holds us secure.',
    you: 'Worship is not something you do alone in your head — it is a "let us," a shared movement toward God. When your own heart feels flat, join the "us": sing with others, and let the rock of your salvation steady you.',
    prayer: 'Lord, rock of my salvation, I come singing and thankful. Draw me into worship with Your people and lift my heart. Amen.',
  },
  'Psalm 150:6': {
    story: 'This is the last verse of the last psalm — the grand finale of the entire book of Psalms. After 150 songs of sorrow, struggle, and praise, the whole collection ends on one all-inclusive command.',
    meaning: '"Let every thing that hath breath praise the Lord. Praise ye the Lord" — the qualification for praising God is simply *breathing*. Every living thing, with no exceptions, is summoned to worship. The Psalms end not with a select choir but with all creation lifting its voice.',
    you: 'If you are breathing, you qualify to praise God — that is the only requirement. Your very breath is on loan from Him, and turning it back to Him in praise is what it was made for. Do not wait to feel worthy; just use the breath you have.',
    prayer: 'Lord, every breath I have is Yours — so with it I praise You. Let my breathing itself become worship today. Amen.',
  },
  'Psalm 34:1': {
    story: 'David wrote this after escaping a deadly situation by pretending to be insane before a foreign king — a low, undignified moment. Yet he emerged resolving to praise God not just afterward, but continually.',
    meaning: '"I will bless the Lord at all times: his praise shall continually be in my mouth" — "at all times" and "continually" leave no gaps: praise is not reserved for the good days. David commits to keeping God\'s praise on his lips through every season, high and low.',
    you: 'Praise is a decision more than a mood — "I *will* bless the Lord." You can worship in the low moments too, not by faking feelings, but by choosing to speak God\'s worth even when life is hard. Praise at all times keeps your heart oriented home.',
    prayer: 'Lord, I will bless You at all times — in the good and the hard. Keep Your praise continually in my mouth. Amen.',
  },
  'Psalm 103:1': {
    story: 'David opens one of the most beloved psalms not by addressing God or others, but by speaking to himself — commanding his own inner being to wake up and worship with everything it has.',
    meaning: '"Bless the Lord, O my soul: and all that is within me, bless his holy name" — David preaches to his own soul, summoning "all that is within" — every faculty, emotion, and thought — to join the praise. Worship here is whole-hearted, not half-distracted.',
    you: 'Sometimes your soul needs to be told what to do. When worship feels distant, do what David did: talk to yourself — "Bless the Lord, O my soul" — and call your whole inner self to attention. Feelings often follow the command, not the other way around.',
    prayer: 'Bless the Lord, O my soul — all that is within me, bless His holy name. Lord, gather my whole heart to worship You. Amen.',
  },
  'John 4:24': {
    story: 'Jesus said this to a Samaritan woman at a well who was arguing about the correct *location* for worship — this mountain or that temple. He lifted her past geography to the heart of what worship actually is.',
    meaning: '"God is a Spirit: and they that worship him must worship him in spirit and in truth" — worship is not about the right building; it is about the right condition. "In spirit" means from the inside, genuinely engaged; "in truth" means according to who God really is. Real worship is inward and honest.',
    you: 'You do not need a special place to worship God — you need a genuine heart. Worship "in spirit and truth" can happen at your kitchen table as fully as in any cathedral. What God seeks is not your location but your honest, engaged spirit.',
    prayer: 'Lord, You are Spirit, and You seek worshippers in spirit and truth. Make my worship real and honest, wherever I am. Amen.',
  },
  'Psalm 96:1-2': {
    story: 'This psalm calls not just Israel but "all the earth" to sing — a global summons to worship. Three times it commands a "new song," as if God\'s mercies keep giving fresh reasons to sing.',
    meaning: '"O sing unto the Lord a new song: sing unto the Lord, all the earth. Sing unto the Lord, bless his name; shew forth his salvation from day to day" — a "new song" is worship kept fresh, matched to today\'s mercies. And worship spills into witness: "shew forth his salvation" — telling others what He has done.',
    you: 'Your worship does not have to be yesterday\'s recycled words. God gives fresh reasons to sing "from day to day" — a new mercy this morning deserves a new song. And that praise naturally becomes testimony: sing it, then show it to someone.',
    prayer: 'Lord, give me a new song today for today\'s mercies. Let my worship overflow into telling others of Your salvation. Amen.',
  },
  'Psalm 145:3': {
    story: 'This is David\'s great alphabet psalm of praise — each verse building on the last to exalt God\'s greatness. In this line he confronts the sheer scale of God, and admits it cannot be measured.',
    meaning: '"Great is the Lord, and greatly to be praised; and his greatness is unsearchable" — "unsearchable" means it cannot be fully explored or reached the bottom of. God is so great that praise can never overstate Him — you will never worship Him beyond His worth.',
    you: 'You can never exaggerate God in worship — His greatness is unsearchable, deeper than any praise can reach. That frees you: no worship you offer is "too much." Aim high; you will still fall short of how great He truly is.',
    prayer: 'Great are You, Lord, and greatly to be praised — Your greatness is beyond searching. I lift the highest praise I have. Amen.',
  },
  'Revelation 4:11': {
    story: 'John was given a vision of heaven itself — a throne, and around it living creatures and elders who never stop worshipping. This verse is the actual song being sung before God\'s throne right now.',
    meaning: '"Thou art worthy, O Lord, to receive glory and honour and power: for thou hast created all things" — heaven\'s worship centres on one word: "worthy." God deserves glory not because worship benefits Him, but simply because of who He is — the Creator of all things. This is the song of the throne room.',
    you: 'When you worship, you are not inventing something new — you are joining a song already echoing in heaven. The elders cast their crowns and cry "worthy." You can lift the same word today and add your voice to the throne-room chorus.',
    prayer: 'Lord, You are worthy to receive glory and honour and power, for You created all things. I join heaven\'s song and call You worthy. Amen.',
  },
  'Hebrews 13:15': {
    story: 'The writer of Hebrews closes his letter to persecuted believers — people with little to offer and much to fear. He tells them what sacrifice they can still bring God: not an animal, but praise, offered continually.',
    meaning: '"By him therefore let us offer the sacrifice of praise to God continually, that is, the fruit of our lips giving thanks to his name" — praise is called a "sacrifice" because sometimes it costs you — you offer it when you do not feel like it. It comes "by him" — through Jesus — and it is "continual," the ongoing fruit of thankful lips.',
    you: 'On the days praise costs you — when the feelings are not there — offering it anyway is a "sacrifice of praise," and it is precious to God precisely because it is hard. Through Jesus, your thankful words are always acceptable, even through gritted teeth.',
    prayer: 'Lord, even when it costs me, I offer the sacrifice of praise through Jesus. Receive the thanks of my lips today. Amen.',
  },
  'Psalm 63:3-4': {
    story: 'David wrote this while a fugitive in the wilderness of Judah — thirsty, hunted, far from the temple. In that desert he made a comparison that reveals what he treasured above his own survival.',
    meaning: '"Because thy lovingkindness is better than life, my lips shall praise thee. Thus will I bless thee while I live: I will lift up my hands in thy name" — David values God\'s love *more than life itself*. That valuation produces worship: praising lips and lifted hands, a whole-body response to a love worth more than breathing.',
    you: 'When you grasp that God\'s love is "better than life" — better than the things you are afraid of losing — worship becomes natural, even in a desert. Lift your hands, not because life is easy, but because His love outweighs everything life could threaten.',
    prayer: 'Lord, Your love is better than life itself. With that truth, I lift my hands and bless You — in the desert as on the mountain. Amen.',
  },
  'Psalm 29:2': {
    story: 'David wrote this psalm picturing a mighty thunderstorm as a display of God\'s voice and power. Amid the thunder he calls the heavenly beings — and us — to give God the honour His name is owed.',
    meaning: '"Give unto the Lord the glory due unto his name; worship the Lord in the beauty of holiness" — "the glory due" implies a debt: God is owed honour, and worship pays what is rightfully His. "The beauty of holiness" means worship adorned with purity — coming to God clean and reverent, not casual.',
    you: 'Worship is partly giving God what He is already owed — the honour due His name. It is not a favour you do Him but a debt of the heart gladly paid. Come today to give Him His due, in reverence and awe.',
    prayer: 'Lord, I give You the glory due Your name and worship You in the beauty of holiness. Receive the honour that is Yours. Amen.',
  },
  'Psalm 42:1-2': {
    story: 'This psalm was written by someone cut off from the temple and taunted with "Where is your God?" Feeling spiritually dry, he reached for an image of raw thirst — a hunted deer desperate for water.',
    meaning: '"As the hart panteth after the water brooks, so panteth my soul after thee, O God. My soul thirsteth for God, for the living God" — the "hart" (deer) pants — gasps — for water. The psalmist does not describe having God; he describes *craving* Him. His dryness has become longing, and longing itself is a form of seeking.',
    you: 'Feeling spiritually dry is not the absence of faith — it can be faith at its thirstiest. That very ache for God, that sense of missing Him, is your soul panting after the living God. The thirst itself proves your soul still knows where the water is.',
    prayer: 'O God, my soul thirsts for You like a deer for water. In my dryness, draw me to Yourself — the living God I long for. Amen.',
  },
  'Psalm 13:1-2': {
    story: 'David begins this psalm with a raw, almost accusing question — repeated four times: "How long?" He feels forgotten by God and stuck in his sorrow. Remarkably, this brutal honesty is what Scripture calls prayer.',
    meaning: '"How long wilt thou forget me, O Lord? for ever? how long wilt thou hide thy face from me? How long shall I take counsel in my soul, having sorrow in my heart daily?" — David does not hide his feeling of abandonment; he pours it out to God directly. Yet by the psalm\'s end he is singing again. Honest lament is a doorway back to trust.',
    you: 'You are allowed to ask God "how long?" — that question is in the Bible, from a man God loved. When God feels distant, do not go silent; go honest. Lament is not the opposite of faith; it is faith refusing to walk away.',
    prayer: 'Lord, how long? I feel forgotten and my heart is heavy — but I bring it to You, not away from You. Meet me here. Amen.',
  },
  'Psalm 63:1': {
    story: 'David wrote this from the Judean wilderness — a literal desert of dust and heat. His outer surroundings matched his inner thirst, and he turned both into a single early-morning cry for God.',
    meaning: '"O God, thou art my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is" — notice he still says "thou art my God" *in* the dry land. His dryness does not cancel the relationship; it intensifies the seeking. He seeks God "early" — making Him the day\'s first pursuit.',
    you: 'In your own "dry and thirsty land," you can still say "thou art my God." Dryness is not a sign God has left — it is an invitation to seek Him early and earnestly. Make Him the first thing you reach for, and the thirst becomes a compass pointing home.',
    prayer: 'O God, You are my God — even in this dry land. Early I seek You; satisfy the thirst of my soul with Yourself. Amen.',
  },
  'Psalm 51:10-12': {
    story: 'David wrote this after his sin with Bathsheba was exposed — his lowest moment. Feeling hollowed out and afraid God\'s presence had left him, he prayed not for escape from consequences, but for his heart and his joy to be restored.',
    meaning: '"Create in me a clean heart, O God; and renew a right spirit within me... restore unto me the joy of thy salvation" — "create" is a word used for making something from nothing; David asks God to do that inside him. And joy is something to be "restored" — it can be lost and given back. He asks God to return it.',
    you: 'If your joy in God has gone dry or your heart feels hardened, you can pray David\'s exact words. You cannot manufacture a clean heart or renewed joy yourself — but you can ask God to create and restore them, and He specializes in exactly that.',
    prayer: 'Create in me a clean heart, O God, and renew a right spirit within me. Restore to me the joy of Your salvation. Amen.',
  },
  'Hosea 6:1-3': {
    story: 'The prophet Hosea calls a wandering, spiritually cold Israel to come home to God. His invitation is gentle and confident — the God they drifted from is as reliably returning as the sunrise and the rains.',
    meaning: '"Come, and let us return unto the Lord... he will revive us... he shall come unto us as the rain, as the latter and former rain unto the earth" — returning to God is met not with rejection but revival. His coming to a dry heart is compared to rain on parched ground — dependable, reviving, life-giving.',
    you: 'When you have drifted and feel far from God, the way back is simple: "let us return." He does not meet returning hearts with a lecture but with rain — reviving what went dry. His coming to you is as certain as the seasons.',
    prayer: 'Lord, I return to You. Revive my dry heart; come to me like rain on thirsty ground and bring me back to life. Amen.',
  },
  'Psalm 143:6': {
    story: 'David, overwhelmed and pursued, remembers God\'s past works and reaches out with a gesture of pure desperation and longing — hands stretched up, soul gaping open like cracked ground begging for rain.',
    meaning: '"I stretch forth my hands unto thee: my soul thirsteth after thee, as a thirsty land. Selah" — stretched-out hands are the posture of a child reaching for a parent, or a beggar for bread. His soul is "a thirsty land" — cracked, dry, waiting. "Selah" means pause and let it sink in.',
    you: 'You do not need eloquent words when your soul is dry — you need only to reach. Stretch out your hands toward God, admit your thirst, and wait. The reaching itself is worship, and God does not ignore an outstretched, thirsty soul.',
    prayer: 'Lord, I stretch out my hands to You; my soul thirsts for You like dry ground. Come and satisfy me. Amen.',
  },
  'Revelation 3:20': {
    story: 'Jesus spoke this to the church at Laodicea — a lukewarm, self-satisfied congregation that had, in effect, left Him standing outside His own church. His response was not to storm off, but to knock and wait.',
    meaning: '"Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will sup with him, and he with me" — Jesus does not break the door down; He knocks and waits to be welcomed. And His goal is intimate — to "sup," to share a meal, the ancient sign of close friendship.',
    you: 'When God feels distant, it may be that He is nearer than you think — standing at the door, knocking, waiting for you to open even a little. He is not far off and angry; He is close and patient, longing to come in and share your table. Open the door.',
    prayer: 'Jesus, You are knocking, and I open the door — come in. Share this moment with me; be close again. Amen.',
  },
  'Jeremiah 29:13': {
    story: 'God speaks this to exiles who feel utterly lost from Him. Alongside His famous promise of "a future and a hope," He tells them exactly how the relationship gets restored — not by their perfection, but by their whole-hearted seeking.',
    meaning: '"And ye shall seek me, and find me, when ye shall search for me with all your heart" — the promise is a guarantee: seek, and you *will* find. The one condition is wholeheartedness — "with all your heart" — not half-hearted, distracted seeking, but a genuine turning of the whole self toward God.',
    you: 'If God feels hidden, this verse is a map with a promise at the end: seek Him with your whole heart and you *will* find Him. He is not playing hide-and-seek to frustrate you; He is findable — and the seeking itself begins to warm the cold heart.',
    prayer: 'Lord, I seek You with all my heart — not halfway, but wholly. You promised I would find You; I hold You to it. Amen.',
  },
  'Psalm 30:11-12': {
    story: 'David closes this psalm of recovery by looking back at what God did with his grief — He did not merely comfort it, He transformed it, turning a funeral into a festival so that praise could not stay silent.',
    meaning: '"Thou hast turned for me my mourning into dancing... to the end that my glory may sing praise to thee, and not be silent. O Lord my God, I will give thanks unto thee for ever" — God\'s purpose in turning mourning to dancing was so David would *sing* — his very "glory" (his soul) could no longer keep quiet. Restored joy naturally overflows into worship.',
    you: 'When God thaws a numb or grieving heart, the sign of life is a song returning. Even if you are not there yet, this is the direction He moves: mourning into dancing, silence into praise. Ask Him to turn your silence back into song.',
    prayer: 'Lord, You turn mourning into dancing. Thaw my heart until it cannot stay silent, and I will give You thanks forever. Amen.',
  },
};
