// Study notes — struggle cluster, part B: tempted, doubtful.
module.exports = {
  '1 Corinthians 10:13': {
    story: 'Paul warned the overconfident Corinthians — surrounded by a city famous for temptation — with Israel\'s wilderness failures. Then he gave the most practical promise about temptation in the Bible.',
    meaning: 'Three facts: your temptation is "common to man" — not uniquely yours; God is faithful and has set a ceiling — "not above that ye are able"; and every temptation ships with an exit — "a way to escape." Look for the door; it was built in.',
    you: 'You are never cornered. In the actual moment of temptation there is always a door — a person to call, a street to cross, a screen to close, a prayer to pray. Train your eyes to find the exit first.',
    prayer: 'Faithful God, in the next temptation, open my eyes to the escape You already built — and give me legs to take it. Amen.',
  },
  'James 1:12': {
    story: 'James wrote to scattered, pressured believers for whom temptation and trial were daily weather. He reframed the entire struggle: endurance is not merely survival — it is championship.',
    meaning: '"Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life" — the athlete\'s wreath awarded after the contest. Every resisted temptation is a round won in a match with a prize at the end.',
    you: 'Your quiet, invisible resistance — the lust refused, the bottle declined, the lie not told — is seen by God and counted toward a crown. You are not just abstaining; you are winning.',
    prayer: 'Lord, when the trial drags on, remind me there is a crown. Help me endure this round — and love You more through it. Amen.',
  },
  'Hebrews 2:18': {
    story: 'The writer of Hebrews explains why the Son of God took on flesh and blood — including this reason: so that when you are being tempted, the One you pray to knows the feeling from inside.',
    meaning: '"In that he himself hath suffered being tempted, he is able to succour them that are tempted" — "succour" means to run to help, like a parent to a crying child. His own temptation in the desert qualified Him as your rescuer in yours.',
    you: 'You are not asking a stranger for help. Jesus felt temptation\'s full weight — He endured it further than anyone who ever gave in. Call Him mid-temptation; running to help is what He does.',
    prayer: 'Lord Jesus, You know how this pull feels. Run to my help right now — succour me in the middle of it. Amen.',
  },
  'Hebrews 4:15-16': {
    story: 'Israel\'s high priest entered God\'s presence on behalf of the people. Hebrews announces a better one: a High Priest who has personally worn our weakness — which changes how we approach the throne.',
    meaning: '"Touched with the feeling of our infirmities... in all points tempted like as we are, yet without sin." Therefore: "come boldly unto the throne of grace" — not crawling, bold — "to obtain mercy, and find grace to help in time of need."',
    you: 'Failure makes you approach God timidly, if at all. This verse commands the opposite posture: boldness — not because you did well, but because the throne is made of grace and the Priest understands.',
    prayer: 'High Priest who understands me, I come boldly — not because I am strong, but because Your throne is grace. Help me now. Amen.',
  },
  'James 4:7': {
    story: 'James was writing to believers being pulled apart by desires and quarrels. His battle plan has a strict order — and the order is the secret.',
    meaning: '"Submit yourselves therefore to God. Resist the devil, and he will flee from you." Submission comes first; resistance second. Resisting without submitting is willpower — it fails. Submitted resistance carries God\'s authority — and the devil runs from that.',
    you: 'You keep resisting without submitting, and losing. Reverse it: first surrender the whole matter to God — then stand. You will discover the enemy is braver against your willpower than against your God.',
    prayer: 'Lord, first I submit — my will, my weakness, this whole fight — to You. Now, in Your authority, I resist. Make him flee. Amen.',
  },
  'Matthew 26:41': {
    story: 'In Gethsemane, hours before the cross, Jesus found His three closest friends asleep on watch. His gentle diagnosis of them became permanent counsel for everyone who has ever meant well and failed.',
    meaning: '"Watch and pray, that ye enter not into temptation" — the battle is won before it starts, in vigilance and prayer. "The spirit indeed is willing, but the flesh is weak" — good intentions have no strength of their own; they need watchfulness.',
    you: 'You do not fail because you want to sin — you fail because you were not watching. Identify your weak hour, your trigger, your open gate — and post prayer there in advance.',
    prayer: 'Jesus, my spirit is willing but my flesh is weak — You said so kindly. Teach me to watch and pray before the hour comes. Amen.',
  },
  'Psalm 119:11': {
    story: 'The longest psalm is one long love song to God\'s Word. This verse explains the psalmist\'s strategy against sin — not stronger fences but a fuller heart.',
    meaning: '"Thy word have I hid in mine heart, that I might not sin against thee" — hiding means storing like treasure. Scripture memorised becomes ammunition available in the exact moment temptation strikes, when your Bible is not open.',
    you: 'Jesus fought the tempter with memorised verses — "It is written." Choose one verse that speaks to your specific weakness and learn it word-for-word this week. Carry a sword, not just a bookshelf.',
    prayer: 'Lord, plant Your Word so deep in me that it speaks before temptation finishes its sentence. Amen.',
  },
  '1 Peter 5:8-9': {
    story: 'Peter knew about the devil\'s hunting habits — Jesus had once told him, "Satan hath desired to have you, that he may sift you as wheat." Writing years later, Peter passes on the survival briefing.',
    meaning: '"Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour" — the roar is real but so is the leash. "Whom resist stedfast in the faith" — lions target the isolated and drowsy, not the alert and anchored.',
    you: 'Temptation is not random — you have an adversary studying your patterns. So study them first: stay sober, stay alert, stay connected to other believers. Lions avoid the fire and the flock.',
    prayer: 'Lord, keep me sober and watchful. When the lion prowls, find me standing firm in faith — and standing near Your people. Amen.',
  },
  'Galatians 5:16': {
    story: 'Paul told the Galatians about the civil war inside every believer — flesh against Spirit. His strategy is surprising: he does not say "fight harder against the flesh." He says walk somewhere else.',
    meaning: '"Walk in the Spirit, and ye shall not fulfil the lust of the flesh" — the promise is spatial: a life actively occupied with the Spirit has no vacancy for the flesh. You defeat darkness by walking in light, not by staring at the dark.',
    you: 'Obsessing over not sinning keeps sin at the centre of attention. Fill the day with the Spirit instead — the Word, prayer, worship, service — and the flesh finds the schedule already full.',
    prayer: 'Holy Spirit, set my pace and fill my day. As I walk with You, starve what pulls against You. Amen.',
  },
  '2 Peter 2:9': {
    story: 'Peter reviews history — Noah rescued from the flood, Lot pulled out of Sodom — and draws a conclusion from the case files: God has an established record of extracting His people.',
    meaning: '"The Lord knoweth how to deliver the godly out of temptations" — knoweth how: this is God\'s expertise, proven over millennia. Your deliverance is not an experiment; it is a repeat performance.',
    you: 'The temptation gripping you has no features God has not dismantled a thousand times before. You are not His hardest case. Trust the specialist — and cooperate with the extraction.',
    prayer: 'Lord, You know how to deliver — You have done it for Your people in every generation. Do it again, for me, here. Amen.',
  },
  'Romans 6:14': {
    story: 'Paul has just told believers they died with Christ and rose to new life. Now he states the legal consequence for the power that used to run their lives.',
    meaning: '"Sin shall not have dominion over you: for ye are not under the law, but under grace" — dominion is ownership language. Sin can still tempt you, but it no longer owns you; grace changed your government.',
    you: 'The voice saying "you will always be like this" is quoting a constitution that was repealed. Sin is a defeated occupier, not your rightful king. Live like a citizen of grace — because you are.',
    prayer: 'Father, sin is not my master anymore — grace is my country now. Help me live free in what Christ made true. Amen.',
  },
  '2 Timothy 2:22': {
    story: 'Paul\'s advice to young Timothy about strong desires is refreshingly unheroic: run away. But the verse has two halves — a direction to flee and a direction to chase, and company for the road.',
    meaning: '"Flee also youthful lusts: but follow righteousness, faith, charity, peace" — fleeing without following leaves a vacuum. "With them that call on the Lord out of a pure heart" — pursuit works best in a pack.',
    you: 'There is no shame in running from what is stronger than you — that is wisdom. But run *toward* something: godly pursuits and godly friends. Escape routes need destinations.',
    prayer: 'Lord, give me quick feet away from temptation and steady feet after righteousness — and companions for the chase. Amen.',
  },
  'Mark 9:24': {
    story: 'A desperate father brought his suffering son to Jesus and half-prayed, "If thou canst do any thing, help us." Jesus turned the "if" back on him — and the man answered with the most honest prayer in the Gospels, through tears.',
    meaning: '"Lord, I believe; help thou mine unbelief" — faith and doubt in the same sentence, both offered to Jesus. And here is the gospel: Jesus healed the boy anyway. Imperfect faith, honestly confessed, was enough.',
    you: 'You do not need to resolve your doubts before coming to Jesus — bring the belief you have and the unbelief you cannot shake, in the same breath. He works with mixed faith; it is the only kind humans have.',
    prayer: 'Lord, I believe — help my unbelief. Take the faith I have and grow it; take the doubt I have and heal it. Amen.',
  },
  'James 1:6': {
    story: 'James has just promised that God gives wisdom generously to all who ask. Then he describes what doubt does to a person — not to their standing with God, but to their stability.',
    meaning: '"He that wavereth is like a wave of the sea driven with the wind and tossed" — the picture is not of a doubter being rejected, but of a mind with no anchor, pushed wherever the last gust blew. Ask "in faith" means ask leaning your weight on God\'s reliability.',
    you: 'Doubt is exhausting because it makes every wind your master. You do not need perfect certainty — you need an anchor: decide in advance that God is good and generous, and let your asking rest there.',
    prayer: 'Generous God, anchor me. I choose to trust Your character even when my feelings toss — and I ask You for wisdom. Amen.',
  },
  'John 20:27-29': {
    story: 'Thomas missed the first resurrection appearance and refused secondhand faith: unless I touch the wounds, I will not believe. A week later Jesus appeared — and went straight to Thomas, wounds first.',
    meaning: 'Jesus did not lecture Thomas; He accommodated him: "Reach hither thy finger." Then the gentle summons: "Be not faithless, but believing." Thomas\'s reply is the highest confession in John\'s Gospel: "My Lord and my God."',
    you: 'Jesus is not threatened by your conditions — He met Thomas\'s exactly. Bring Him your specific doubts; He deals in evidence and presence. And He calls you specially blessed: one who believes without touching.',
    prayer: 'Lord Jesus, meet my doubts the way You met Thomas\'s — personally, patiently. Bring me to say: my Lord and my God. Amen.',
  },
  'Hebrews 11:1': {
    story: 'Hebrews 11 is Scripture\'s hall of fame — Abel, Noah, Abraham, Moses — and it opens with a definition of the thing they all had in common. Notice what the definition is not: certainty about everything.',
    meaning: '"Faith is the substance of things hoped for, the evidence of things not seen" — substance means solid ground under your hopes; evidence means conviction about realities your eyes cannot yet verify. Faith is not the absence of questions; it is confidence in a Person amid them.',
    you: 'You can hold unanswered questions and real faith at the same time — every hero in Hebrews 11 did. Faith is not knowing how; it is trusting Who.',
    prayer: 'Lord, give me faith that stands on Your promises even where my eyes see nothing yet. Be my substance and my evidence. Amen.',
  },
  'Isaiah 55:8-9': {
    story: 'God spoke these words through Isaiah while offering pardon so generous it strained belief. Anticipating the objection — "that seems too easy, too unlike how we operate" — God explained the gap.',
    meaning: '"My thoughts are not your thoughts... as the heavens are higher than the earth, so are my ways higher than your ways" — the distance is not a wall but a comfort in context: His mercy operates on a scale your logic cannot audit.',
    you: 'Some of your doubt is just your mind demanding that an infinite God fit inside it. He will not — and that is good news. You do not need to understand His ways to trust their height.',
    prayer: 'God of higher ways, where I cannot trace You, help me trust You. Be bigger than my understanding — and better. Amen.',
  },
  'Proverbs 3:5-6': {
    story: 'This father-to-son proverb may be the most memorised passage in the Bible. It asks for the one thing harder than obedience in a crisis: the transfer of confidence from your own analysis to God\'s direction.',
    meaning: '"Trust in the Lord with all thine heart; and lean not unto thine own understanding" — lean is a weight word: where do you rest your weight when deciding? "In all thy ways acknowledge him" — bring Him into every path, "and he shall direct thy paths" — He straightens the road as you walk it.',
    you: 'Your understanding is a good tool and a terrible foundation. Use your mind fully — then rest your weight on God. Acknowledged paths get directed; self-leaning paths get tangled.',
    prayer: 'Lord, I move my weight off my own understanding and onto You. I acknowledge You in every plan today — direct my paths. Amen.',
  },
  'Jude 1:22': {
    story: 'Jude wrote urgently about defending the faith against corruption — strong, fierce language. Yet in his closing instructions comes this startlingly tender command about how to treat strugglers.',
    meaning: '"And of some have compassion, making a difference" — doubters are to be met with mercy, not scolding. The early church was commanded to be gentle with wavering people, because gentleness — not shame — is what restores them.',
    you: 'If God\'s people are commanded to show your doubts compassion, be sure God Himself does. Your questions do not disqualify you from His family — they are handled there with mercy. Extend the same to other doubters.',
    prayer: 'Merciful Father, thank You that doubters get compassion in Your house. Handle my questions gently — and make me gentle too. Amen.',
  },
  'Romans 10:17': {
    story: 'Paul, explaining how anyone comes to believe, traces faith back to its food supply. Faith is not manufactured by effort — it grows by hearing.',
    meaning: '"Faith cometh by hearing, and hearing by the word of God" — faith is the child of exposure to God\'s Word. Starve the hearing and faith weakens; feed it and faith comes — that is a promise about supply lines.',
    you: 'Doubt often means malnourishment, not defect. When did you last actually feed on Scripture — heard, read, spoken aloud? Increase the intake and watch what "cometh."',
    prayer: 'Lord, feed my faith — open Your Word to me daily, and let hearing do in me what straining never could. Amen.',
  },
  'Psalm 77:11-12': {
    story: 'Asaph wrote Psalm 77 from insomnia and spiritual crisis — "Will the Lord cast off for ever?" He climbed out by a deliberate discipline: forcing his memory to testify against his mood.',
    meaning: '"I will remember the works of the Lord... I will meditate also of all thy work" — three verbs: remember, meditate, talk. When present feelings say God is gone, Asaph cross-examines them with God\'s documented past.',
    you: 'Your doubt has a short memory. Fight it with the archive: write down what God has already done in your life — answered prayers, rescues, providences — and read the list aloud when the night gets long.',
    prayer: 'Faithful God, I remember Your works — in Scripture and in my own story. Let the record speak louder than tonight\'s doubt. Amen.',
  },
  'Habakkuk 3:17-18': {
    story: 'Habakkuk argued with God for two chapters about injustice — and got answers that did not remove the coming disaster. His book ends with the most defiant "yet" in Scripture, sung while expecting economic collapse.',
    meaning: '"Although the fig tree shall not blossom... yet I will rejoice in the Lord" — six failures listed, every income stream dead, and joy chosen anyway. Not joy *about* circumstances; joy *in* the God of his salvation.',
    you: 'Faith\'s deepest form is not believing God will fix everything soon — it is rejoicing in Him even if nothing visibly works out. Practice Habakkuk\'s grammar: name your empty fields, then say "yet."',
    prayer: 'God of my salvation, though the fields are empty — yet I will rejoice in You. Be my joy when nothing else supplies it. Amen.',
  },
  'Mark 11:24': {
    story: 'Passing a withered fig tree, Jesus astonished His disciples with what prayer can move — mountains, He said. Then He gave them the inner posture of that kind of praying.',
    meaning: '"What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them" — praying with reception, not suspicion; approaching God as a giver, not a gatekeeper. Faith prays expecting, inside God\'s will and timing.',
    you: 'Examine how you pray: are you asking while braced for no? Faith grows by practicing expectation — pray specifically, thank Him in advance, and watch for answers so you notice them when they land.',
    prayer: 'Lord, teach me expectant prayer — asking as from a Father who gives. I believe; grow my believing as I pray. Amen.',
  },
};
