// Study notes — struggle cluster, part A: angry, guilty.
module.exports = {
  'Ephesians 4:26': {
    story: 'Paul wrote to the Ephesians about life inside a new community of very different people — Jews and Gentiles, slaves and masters — where friction was guaranteed. His counsel assumes anger will happen; the question is what you do before sundown.',
    meaning: '"Be ye angry, and sin not" — anger itself is an emotion God built into you; it becomes sin by what it grows into. "Let not the sun go down upon your wrath" — deal with it today, because overnight anger ferments into something darker.',
    you: 'You do not have to feel guilty for feeling angry. But anger is like milk — it does not keep. Name it, pray it, and where possible settle it before you sleep, or tomorrow it will have soured into bitterness.',
    prayer: 'Lord, I am angry — I bring it to You before the sun goes down. Keep me from sinning in it, and settle my heart tonight. Amen.',
  },
  'Proverbs 15:1': {
    story: 'Solomon collected these proverbs to train young leaders in real-life wisdom. This one describes something he must have watched a thousand times in court: how one person\'s tone decides whether a room catches fire.',
    meaning: '"A soft answer turneth away wrath" — soft means gentle, not weak. It absorbs heat instead of reflecting it. "Grievous words stir up anger" — harsh words are bellows on coals; they never win the fight, they enlarge it.',
    you: 'In your next heated moment you hold real power: your reply sets the temperature. Lowering your voice is not losing — it is taking control of where the conversation goes.',
    prayer: 'God, when heat rises today, give me the strength of a soft answer. Make me a cooler of fires, not a fanner of them. Amen.',
  },
  'Psalm 37:8': {
    story: 'David wrote Psalm 37 as an old man who had spent decades watching evil people prosper — plenty of reason for rage. His conclusion after a lifetime: anger at the wicked mostly damages the one carrying it.',
    meaning: '"Cease from anger, and forsake wrath" — lay it down like a tool that is cutting you. "Fret not thyself in any wise to do evil" — stewing over wrongs slowly bends you toward doing wrong yourself.',
    you: 'Your anger may be entirely justified — and still be poisoning you. Ceasing is not saying the wrong did not matter; it is refusing to let their wrong reshape your heart.',
    prayer: 'Lord, I release the anger I have been feeding. It is not making anything right — You will. Cool me down. Amen.',
  },
  'Romans 12:19': {
    story: 'Paul wrote this to believers in Rome — people living under an empire that would soon persecute them brutally. His instruction for the deeply wronged came with a quotation from God Himself: vengeance is Mine.',
    meaning: '"Avenge not yourselves, but rather give place unto wrath" — step back and leave room for God\'s justice. "I will repay, saith the Lord" — the debt is not cancelled; it is transferred to a Judge who misses nothing.',
    you: 'Letting go of revenge is not letting them get away with it — it is handing the case to a higher court. You were never strong enough to carry both the wound and the gavel. Give God the gavel.',
    prayer: 'Righteous Judge, I hand over the case — the wrong, the evidence, the sentence. Free my hands and heal my heart. Amen.',
  },
  'Proverbs 16:32': {
    story: 'In Solomon\'s world, the celebrated men were warriors who took cities. This proverb dares to rank someone higher: the person who, in the moment of provocation, governs their own spirit.',
    meaning: '"He that is slow to anger is better than the mighty" — self-rule outranks conquest. Taking a city requires strength for a day; ruling your spirit requires strength every day.',
    you: 'Every time you hold your temper, heaven counts it a greater victory than anything trending or trophied. Your quiet self-control today is mightier than you know.',
    prayer: 'Lord, make me slow to anger. Help me win the harder battle — the one inside — before I fight any other. Amen.',
  },
  'James 1:19-20': {
    story: 'James, the brother of Jesus, wrote the New Testament\'s most practical letter. Here he gives a three-part speed limit for conflict, and a hard truth about what anger can and cannot build.',
    meaning: '"Swift to hear, slow to speak, slow to wrath" — reverse of our instincts, which are slow to hear and swift to everything else. "The wrath of man worketh not the righteousness of God" — your fury never manufactures His justice.',
    you: 'Try the sequence literally in your next conflict: listen first, long; speak second, slowly; let anger come last, if at all. You cannot rage anyone into righteousness — including yourself.',
    prayer: 'Father, re-order me: quick ears, slow tongue, slower temper. Do Your righteousness in me the way anger never could. Amen.',
  },
  'Ecclesiastes 7:9': {
    story: 'The Preacher of Ecclesiastes examined every path a life can take. On anger, his verdict is about real estate: what you allow to *rest* in your heart takes up residence there.',
    meaning: '"Be not hasty in thy spirit to be angry" — a short fuse is a character flaw, not a personality trait. "Anger resteth in the bosom of fools" — visiting anger is human; hosting it long-term is folly.',
    you: 'Anger will knock on everyone\'s door. The question is whether you give it a room. Check today: is there an old anger that has quietly moved in and unpacked?',
    prayer: 'Lord, search my heart for anger that has taken up residence. I evict it today — fill the room with Your peace instead. Amen.',
  },
  'Proverbs 14:29': {
    story: 'This proverb draws the connection between temper and understanding: patience is not just niceness — it is intelligence about people, situations, and yourself.',
    meaning: '"He that is slow to wrath is of great understanding" — patience gives time to actually comprehend what is happening. "He that is hasty of spirit exalteth folly" — the quick-tempered put their foolishness on a pedestal for all to see.',
    you: 'The pause between provocation and response is where wisdom lives. Even three slow breaths create space for understanding to speak before folly grabs the microphone.',
    prayer: 'God, lengthen my fuse. In the pause, give me understanding — of the other person, of myself, and of what You want. Amen.',
  },
  'Colossians 3:8': {
    story: 'Paul told the Colossians that becoming a Christian is like changing clothes: the old life comes off, the new goes on. Anger sits at the top of the laundry list of what must come off.',
    meaning: '"Put off all these; anger, wrath, malice" — pictured as garments you remove, deliberately, one by one. They were your old outfit; they no longer fit who you are becoming in Christ.',
    you: 'Anger is not "just how I am" — it is something you are wearing, and you can take it off. Each morning, choose your clothes: kindness and patience fit the new you far better.',
    prayer: 'Lord Jesus, today I take off anger, wrath, and bitterness like an old coat. Dress me in Your character instead. Amen.',
  },
  'Proverbs 19:11': {
    story: 'This proverb was written for future kings and leaders — people who would be wronged constantly and publicly. Its counsel: the most impressive response to many offenses is to walk past them.',
    meaning: '"The discretion of a man deferreth his anger" — wisdom knows how to postpone rage until facts are in, and often forever. "It is his glory to pass over a transgression" — overlooking an offense is not weakness; it is splendour.',
    you: 'Not every wrong deserves a war. Some offenses shrink to nothing if you simply decline to pick them up. Choosing which battles not to fight is a crown, not a surrender.',
    prayer: 'Father, give me discretion — to defer my anger, to pass over small wrongs, and to look a little more like You. Amen.',
  },
  'Ephesians 4:31-32': {
    story: 'Paul lists six forms anger takes — bitterness, wrath, anger, clamour, evil speaking, malice — like a doctor naming the stages of one disease. Then he prescribes the cure, and it is not willpower. It is memory.',
    meaning: '"Forgiving one another, even as God for Christ\'s sake hath forgiven you" — the engine of forgiveness is remembering how much you were forgiven. Kindness flows downhill from the cross to your conflicts.',
    you: 'When forgiving feels impossible, do not look harder at the person — look longer at the cross. The debt God cancelled for you dwarfs any debt owed to you. Forgiven people forgive.',
    prayer: 'Father, You forgave me everything in Christ. From that same well, let me draw forgiveness for the one who hurt me. Amen.',
  },
  'Psalm 4:4': {
    story: 'David wrote this evening psalm during a season of slander and betrayal. His counsel for nighttime anger is remarkably modern: feel it, examine it in the quiet, and refuse to act from it.',
    meaning: '"Stand in awe, and sin not" — some translations read "be angry, and sin not." "Commune with your own heart upon your bed, and be still" — take the anger to your pillow for review, not for rehearsal.',
    you: 'Tonight, instead of replaying the offense, interview your anger before God: what is really underneath it? Then be still. Anger examined in His presence loses its power to steer you.',
    prayer: 'Lord, on my bed tonight I open my anger to You. Search it with me, quiet it in me, and give me sleep in peace. Amen.',
  },
  '1 John 1:9': {
    story: 'John wrote to believers unsettled by teachers claiming sin either did not matter or could not be forgiven. His answer is the clearest cleansing promise in the Bible — with only one condition: honesty.',
    meaning: '"If we confess" — confession is simply agreeing with God about what happened, hiding nothing. "He is faithful and just to forgive" — forgiveness is guaranteed by His character, not your worthiness. "Cleanse us from ALL unrighteousness" — no residue left.',
    you: 'You have been carrying what God has offered to erase. Tell Him plainly, today, the thing you keep circling. The promise activates on honesty — and it covers all of it.',
    prayer: 'Father, I confess it to You now, without excuses. Thank You that You are faithful and just — forgive me and make me clean. Amen.',
  },
  'Romans 8:1': {
    story: 'Paul spent seven chapters of Romans diagnosing human guilt — including his own wretched struggle in chapter 7. Then chapter 8 opens like a courtroom door flung wide: no condemnation.',
    meaning: '"Therefore now no condemnation" — the verdict is rendered in the present tense, now, not after you improve. "To them which are in Christ Jesus" — location is everything: the accused stands inside Christ, so the sentence fell on Him already.',
    you: 'Condemnation replays your record; the Spirit speaks of your standing. If you are in Christ, the case is closed — what feels like God\'s accusation is not His voice.',
    prayer: 'Jesus, I am in You — so I refuse the condemnation that keeps knocking. The verdict is in: no condemnation. I receive it. Amen.',
  },
  'Psalm 103:12': {
    story: 'David — a man whose sins were written into Scripture for all history to read — composed this psalm cataloguing God\'s benefits. At its centre he reached for the largest distance his geography could express.',
    meaning: '"As far as the east is from the west" — north and south meet at the poles; east and west never meet. God chose the one direction pair with infinite distance: that is how far He removes your transgressions.',
    you: 'Your sin is not filed away for later reference — it is removed, in a direction that never doubles back. When memory drags it near, remember: God has relocated it beyond retrieval.',
    prayer: 'Father, thank You that my sin has been carried away in a direction that never returns. Help me stop retrieving what You removed. Amen.',
  },
  'Isaiah 1:18': {
    story: 'Isaiah\'s book opens with God\'s lawsuit against a rebellious nation — charges, evidence, guilt beyond dispute. Then, astonishingly, the offended party leans forward and offers to talk.',
    meaning: '"Come now, and let us reason together" — God invites conversation, not execution. "Though your sins be as scarlet, they shall be as white as snow" — scarlet was a fast dye that never washed out. God promises the impossible: permanent stains gone.',
    you: 'You assume your history is dye-fast — too deep, too repeated, too red. The God who knows every detail says: come, let us talk, and I will make you snow-white. The invitation still stands.',
    prayer: 'God, I come to reason with You, stains and all. Do what no scrubbing of mine could do — make me white as snow. Amen.',
  },
  'Romans 3:23-24': {
    story: 'Paul has just spent two and a half chapters proving that everyone — religious and pagan alike — stands guilty. Then in one breath he levels the ground and opens the gift.',
    meaning: '"All have sinned" — the same "all" then meets grace: "being justified freely by his grace." Justified is a court word — declared right. "Freely" translates a word meaning "without cause, gift-wise" — paid for by Christ\'s redemption, not your record.',
    you: 'You are not uniquely disqualified — everyone fell short. And the same doorway is open to everyone: not earning, receiving. Guilt says "do more"; grace says "it is done, take it."',
    prayer: 'Father, I stop trying to pay what Christ already paid. I receive justification as a gift — freely, by grace, today. Amen.',
  },
  'Psalm 32:5': {
    story: 'David wrote Psalm 32 after the darkest cover-up of his life. He describes the physical toll of hidden sin — bones aging, strength drying up — and then the moment everything changed: he stopped hiding.',
    meaning: '"I acknowledged my sin unto thee, and mine iniquity have I not hid... and thou forgavest" — notice the speed: confession and forgiveness in the same verse. The agony was long only because the hiding was.',
    you: 'The heaviness you carry may not be the sin itself but the concealment of it. God is not waiting to humiliate you — He is waiting to forgive you. The moment you uncover it, He covers it.',
    prayer: 'Lord, I am done hiding. Here is what I did. Forgive the iniquity of my sin — and lift the weight I was never meant to carry. Amen.',
  },
  'Psalm 51:10': {
    story: 'After the prophet Nathan exposed David\'s adultery and murder, David wrote Psalm 51 — the rawest confession in Scripture. By verse 10 he asks for something beyond pardon: he asks to be remade.',
    meaning: '"Create in me a clean heart" — the verb "create" is the same used for creation from nothing. David is not asking for a repair; he is asking for the miracle only God performs: a new heart, a right and steadfast spirit.',
    you: 'You cannot scrub your own heart clean — but you were never asked to. Pray the boldest prayer forgiveness allows: not "help me improve," but "create in me something new."',
    prayer: 'Create in me a clean heart, O God, and renew a right spirit within me. Make new what I could only stain. Amen.',
  },
  'Hebrews 8:12': {
    story: 'The writer of Hebrews quotes God\'s promise of a new covenant — the upgrade Israel\'s prophets longed for. Its crowning clause is about the divine memory, and what God chooses to do with it.',
    meaning: '"Their sins and their iniquities will I remember no more" — God is not forgetful; He is deliberate. Not remembering means He will never bring them up again — not at your next failure, not at judgment, never.',
    you: 'You keep re-reading a file God has shredded. If He will never mention it again, who are you listening to when it gets mentioned? Answer accusation with covenant: "He remembers it no more."',
    prayer: 'Merciful Father, You have chosen to remember my sins no more. Teach my memory to honour Your mercy. Amen.',
  },
  'Micah 7:19': {
    story: 'Micah closes his book marveling: "Who is a God like unto thee, that pardoneth iniquity?" His final image is physical — God taking sins in hand and hurling them into the ocean.',
    meaning: '"He will subdue our iniquities" — sin is treated as an enemy God defeats, not just a debt He waives. "Thou wilt cast all their sins into the depths of the sea" — the depths, not the shallows where tides wash things back.',
    you: 'What you keep fishing up, God threw into the deepest trench on purpose. No diving expeditions. The sea floor keeps what God sinks.',
    prayer: 'God like no other, You drowned my sins in the depths. When I row back to look for them, turn my boat around. Amen.',
  },
  '2 Corinthians 5:17': {
    story: 'Paul knew about fresh starts — he had persecuted Christians before Christ remade him on the Damascus road. Writing to Corinth, he compressed the miracle of conversion into one sentence.',
    meaning: '"If any man be in Christ, he is a new creature" — literally a new creation, the same word as Genesis. "Old things are passed away; behold, all things are become new" — your old identity is not renovated; it is replaced.',
    you: 'Guilt insists you are your history. This verse insists you are a new creation whose history died with Christ. You are not the person who did those things — behold, new.',
    prayer: 'Creator God, I am in Christ — a new creation. Help me live today as who I now am, not who I used to be. Amen.',
  },
  'Isaiah 43:25': {
    story: 'Israel had earned exile through centuries of rebellion — God spends the surrounding verses listing their failures. Then comes this verse, where God explains why He wipes the record anyway. The reason is not them.',
    meaning: '"I, even I, am he that blotteth out thy transgressions for mine own sake" — the doubled "I" is emphatic: this is God\'s personal doing, motivated by His own character and glory. "Will not remember thy sins" — erased and unarchived.',
    you: 'Your forgiveness does not rest on the quality of your repentance but on the character of your God. He blots out sin because of who He is — which means it is as secure as He is.',
    prayer: 'Lord, You blot out my transgressions for Your own sake. I rest my forgiveness on Your character, not my performance. Amen.',
  },
  '1 John 2:1': {
    story: 'John, now elderly, writes like a father: "My little children." He aims for them to stop sinning — but he immediately covers the moment they fail, with a courtroom picture of who stands up for them.',
    meaning: '"If any man sin, we have an advocate with the Father, Jesus Christ the righteous" — an advocate is a defense lawyer. When you fail, Jesus does not join the accusation; He rises to plead His own blood on your behalf.',
    you: 'The moment after you sin is exactly when the enemy says "hide." It is also exactly when your Advocate is already speaking for you. Run toward the courtroom, not away — your lawyer has never lost.',
    prayer: 'Jesus Christ the Righteous, my Advocate — I failed today, and I come straight to You. Plead for me; restore me. Amen.',
  },
};
