// Study notes — struggle cluster, part C: discouraged, insecure, jealous.
module.exports = {
  'Galatians 6:9': {
    story: 'Paul wrote to churches tempted to quit on generosity and goodness because results were slow. His encouragement borrows from the farm: between sowing and reaping there is always an unglamorous middle.',
    meaning: '"Let us not be weary in well doing: for in due season we shall reap, if we faint not" — "due season" means the harvest has a set date you cannot see. The only way to lose the crop is to stop before it arrives.',
    you: 'Your faithful, unnoticed work — parenting, serving, praying, giving — is seed in the ground, not seed wasted. The silence between planting and harvest is normal farming. Do not dig up the field in week three.',
    prayer: 'Lord, I am tired of doing good without seeing results. Renew me — I choose not to faint before Your due season. Amen.',
  },
  'Deuteronomy 31:8': {
    story: 'Moses spoke these words directly to Joshua in front of all Israel — a public transfer of courage to a man inheriting an impossible job. The promise was about who travels in front.',
    meaning: '"The Lord, he it is that doth go before thee" — before: God arrives at your future first and prepares it. "He will be with thee, he will not fail thee... fear not, neither be dismayed" — ahead of you, beside you, never failing.',
    you: 'Discouragement stares at tomorrow and sees only your inadequacy in it. But tomorrow is already occupied — God went ahead. You will not walk into any room He has not entered first.',
    prayer: 'Lord who goes before me, thank You that my future is already visited territory. I follow You into it unafraid. Amen.',
  },
  '2 Corinthians 4:16-18': {
    story: 'Paul lists his sufferings in this letter — beatings, shipwrecks, sleepless nights — then explains the accounting system that kept him from quitting: two columns, weighed against each other.',
    meaning: '"Though our outward man perish, yet the inward man is renewed day by day" — decay outside, renewal inside, daily. "Our light affliction, which is but for a moment, worketh for us a far more exceeding and eternal weight of glory" — on God\'s scales, glory outweighs affliction beyond comparison.',
    you: 'Your discouragement is doing math with only one column. Add the other: inner renewal today, eternal glory ahead. Look "not at the things which are seen" — the unseen is where your investment is compounding.',
    prayer: 'Father, renew my inner self today even while the outer struggles. Fix my eyes on the unseen weight of glory. Amen.',
  },
  '1 Corinthians 15:58': {
    story: 'Paul ends fifty-seven verses on the resurrection with a "therefore" — because Christ rose and you will too, here is how to work today. The connection matters: eternity is what makes effort meaningful.',
    meaning: '"Be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is not in vain in the Lord" — not in vain: because resurrection is real, nothing done for Christ evaporates. Every unseen act is on eternal record.',
    you: 'The lie of discouragement is "it makes no difference." Resurrection answers: everything done in the Lord survives — every kindness, every prayer, every faithful year. Abound; the accounting is safe.',
    prayer: 'Risen Lord, keep me steadfast when I cannot see the point. My labour in You is not in vain — I believe it. Amen.',
  },
  'Nehemiah 8:10': {
    story: 'The returned exiles heard the Law read aloud and broke down weeping over their failures. Nehemiah\'s response is surprising: he sent them to feast — because he knew what actually strengthens a crushed people.',
    meaning: '"The joy of the Lord is your strength" — not joy in circumstances (theirs were rubble) but joy in the Lord: who He is, what He has done, His delight in them. That joy is load-bearing; it holds people up.',
    you: 'You cannot fight discouragement with willpower — you fight it with joy, deliberately taken: worship, gratitude, remembering His goodness. Joy is not the reward after strength; it is the source of it.',
    prayer: 'Lord, be my joy today — and let that joy be my strength. Lift what heaviness cannot lift. Amen.',
  },
  'Psalm 31:24': {
    story: 'David closes this psalm — written from distress, slander, and being "forgotten as a dead man" — by turning to address everyone else in the same situation. His final word is a rallying cry.',
    meaning: '"Be of good courage, and he shall strengthen your heart, all ye that hope in the Lord" — the order matters: you supply courage-choosing hope; He supplies strengthened hearts. Hope in the Lord is never left unreinforced.',
    you: 'Courage is not a feeling you wait for — it is a stance you take, and God meets it with strength. Take the stance today: hope in the Lord, and let Him do the strengthening.',
    prayer: 'Lord, I take courage — not because I feel strong but because my hope is in You. Strengthen my heart as You promised. Amen.',
  },
  'Hebrews 12:1-2': {
    story: 'After the hall of faith in chapter 11, the writer pictures a stadium: witnesses in the stands, a race marked out, and one place to fix your eyes — the Finisher who ran it first.',
    meaning: '"Let us run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith" — lay aside weights, run your assigned course, and aim your gaze: Jesus endured the cross "for the joy that was set before him." Endurance runs on focus.',
    you: 'Runners fall where they look. Discouragement stares at the distance left or the runners passing you — look at Jesus instead. He authored your faith; He will finish it. Your race is His project.',
    prayer: 'Author and Finisher of my faith, I drop the weights and fix my eyes on You. Pace me to the end of my race. Amen.',
  },
  'Psalm 139:14': {
    story: 'David composed this psalm about being fully known by God — including a meditation on his own making. He looks at his own existence and comes to a conclusion insecurity never reaches: praise.',
    meaning: '"I will praise thee; for I am fearfully and wonderfully made" — fearfully means awe-inspiringly, with reverent care; wonderfully means distinct, set apart. "Marvellous are thy works" — and David counts himself among them.',
    you: 'You critique what God crafted. This verse teaches a different response to your own reflection: praise the Maker. You are not a mistake with potential — you are a marvel with a purpose.',
    prayer: 'Creator, I stop insulting Your workmanship. I am fearfully and wonderfully made — and I praise You for it. Amen.',
  },
  'Isaiah 43:1-4': {
    story: 'To a nation feeling worthless and disposable in exile, God delivered a series of declarations — ownership, presence, and then an astonishing valuation spoken directly: you are precious to Me.',
    meaning: '"Thou wast precious in my sight, thou hast been honourable, and I have loved thee" — precious is treasure language; honourable is dignity language; loved is the ground of both. God prices you by His love, not your performance.',
    you: 'The market keeps re-pricing you — by looks, output, followers, income. God\'s valuation was set in love and does not float. Precious, honoured, loved: that is your fixed worth.',
    prayer: 'Lord, when I feel worthless, read me Your valuation again: precious, honourable, loved. I take Your word for my worth. Amen.',
  },
  'Ephesians 2:10': {
    story: 'Paul has just finished saying salvation is entirely by grace, not works. Then he flips the coin: saved people are themselves a work — God\'s work — with work prepared and waiting.',
    meaning: '"We are his workmanship" — the Greek word is poiema, from which we get "poem": you are God\'s crafted composition. "Created in Christ Jesus unto good works, which God hath before ordained that we should walk in them" — your assignments were laid out before you arrived.',
    you: 'You are not an accident looking for a purpose — you are a poem with pre-prepared paths. Today\'s good works were set out for you like clothes laid on a bed. Walk in them.',
    prayer: 'Master Craftsman, I am Your workmanship. Lead me into the good works You prepared for me before I existed. Amen.',
  },
  'Jeremiah 1:5': {
    story: 'When God called young Jeremiah, the boy protested he could not speak and was too young. God\'s answer went back before Jeremiah\'s birth — to a knowing, a setting apart, an appointment.',
    meaning: '"Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee" — known before formed; consecrated before born. Identity and calling precede existence in the mind of God.',
    you: 'Your insecurity says you are unqualified. God\'s timeline says you were designed *for* this — known, set apart, and appointed before your first breath. He does not draft randomly.',
    prayer: 'Lord, You knew me before You formed me. I lay down "I can\'t" — You appointed me before I was born. Amen.',
  },
  '1 Peter 2:9': {
    story: 'Peter wrote to believers who were social outsiders — mocked, marginalised, homeless in their own culture. He handed them a stack of titles originally given to Israel at Sinai, now theirs.',
    meaning: '"A chosen generation, a royal priesthood, an holy nation, a peculiar people" — chosen, royal, holy, treasured ("peculiar" means God\'s own possession). Purpose follows: to "shew forth the praises of him who hath called you out of darkness into his marvellous light."',
    you: 'The world may file you under ordinary. Heaven files you under chosen, royal, holy, treasured. Read your titles again — then live the job description: display His praises.',
    prayer: 'Father, I take the titles You gave me — chosen, royal, holy, Yours. Let my life show forth Your praise today. Amen.',
  },
  'Romans 8:31': {
    story: 'After promising that God works all things for good and glorification is certain, Paul asks the question that ends all arguments — a question he leaves hanging because no answer can stand.',
    meaning: '"If God be for us, who can be against us?" — "for us" is the settled fact proven at the cross. Opposition exists, but no opponent outweighs the advocate. The question expects silence.',
    you: 'List everyone whose approval you crave and everyone whose criticism you fear. Now set the list against four words: God is for you. The math is over.',
    prayer: 'God, You are for me — You proved it with Your own Son. Quiet every other verdict in my head today. Amen.',
  },
  'Zephaniah 3:17': {
    story: 'Zephaniah\'s short book thunders with judgment — until its final paragraphs, where the storm breaks into the most tender picture of God in the prophets: a warrior who sings.',
    meaning: '"He will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing" — three escalations: God delights in you, quiets you with His love, and — astonishingly — sings over you, the way a parent sings over a child.',
    you: 'You imagine God tolerating you at best. This verse says He rejoices over you — audibly. Somewhere over your life, right now, there is a song being sung by the Mighty One in your midst.',
    prayer: 'Lord my God in the midst of me, quiet me with Your love today — and let me live like someone You sing over. Amen.',
  },
  'Galatians 2:20': {
    story: 'Paul is describing the exchange at the heart of his existence — the old self-executed, Christ moved in. The verse ends by getting intensely personal about who the cross was for.',
    meaning: '"I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me... who loved me, and gave himself for me" — the plural gospel becomes singular: loved *me*, gave Himself for *me*. Identity now rests on that exchange.',
    you: 'Say the last phrase with your own name in it — "who loved ___, and gave Himself for ___." Insecurity cannot survive being personally died for. Your worth was settled at Calvary, individually.',
    prayer: 'Lord Jesus, You loved me and gave Yourself for me. Let that be my identity today — Christ living in me. Amen.',
  },
  'Matthew 10:29-31': {
    story: 'Sending His disciples into hostile territory, Jesus armed them not with strategies but with a statement about sparrows — the cheapest life in the market, two for a farthing.',
    meaning: '"One of them shall not fall on the ground without your Father" — even sparrow deaths are attended by God. "The very hairs of your head are all numbered" — not counted once, but numbered, tracked individually. "Ye are of more value than many sparrows."',
    you: 'God\'s attention to you is not general but granular — down to the hair. If His eye is on the sparrow and His count is on your head, your fear of being overlooked has no ground left.',
    prayer: 'Father, You number my hairs and attend the sparrows. I matter to You in detail — help me live unafraid. Amen.',
  },
  'Colossians 2:10': {
    story: 'False teachers in Colossae were selling spiritual upgrades — secret knowledge, extra rituals, angelic intermediaries. Paul\'s rebuttal is one word about what believers already are in Christ.',
    meaning: '"And ye are complete in him, which is the head of all principality and power" — complete: filled full, lacking nothing essential. In Christ you are not a starter kit awaiting add-ons; the fullness is already conferred.',
    you: 'Insecurity is a completeness problem — the sense of missing something others have. In Christ, the verdict is "complete." Stop shopping for what you already possess in Him.',
    prayer: 'Lord Jesus, in You I am complete — nothing essential missing. Silence the salesmen of "not enough." Amen.',
  },
  'Genesis 1:27': {
    story: 'The Bible\'s first chapter builds to one creature made unlike all the others — not "after their kind" like animals, but after God\'s own likeness. The text slows into poetry to mark the moment.',
    meaning: '"So God created man in his own image, in the image of God created he him; male and female created he them" — image-bearing is the bedrock of human worth: every person carries a stamped resemblance to the Creator, prior to any achievement.',
    you: 'Your dignity predates your resume. Before you did anything — and regardless of what has been done to you — you bear God\'s image. That is the floor no failure can fall through.',
    prayer: 'Creator, I bear Your image. Ground my worth there — beneath achievement, beyond opinion, unshakeable. Amen.',
  },
  'Psalm 37:1-4': {
    story: 'David opens this psalm addressing the oldest resentment: watching wrongdoers flourish. His prescription replaces the sideways stare with a fourfold redirection — trust, do good, delight, commit.',
    meaning: '"Fret not thyself because of evildoers, neither be thou envious" — fretting is slow burning. "They shall soon be cut down like the grass" — their flourish is seasonal. "Delight thyself also in the Lord; and he shall give thee the desires of thine heart" — delight reshapes desire until God can safely grant it.',
    you: 'Envy is attention pointed sideways. Point it up: make God your delight — worship, gratitude, His Word — and watch your desires change into ones He delights to fulfil.',
    prayer: 'Lord, I stop staring sideways at others\' green grass. Be my delight — and shape the desires of my heart. Amen.',
  },
  'Proverbs 14:30': {
    story: 'Millennia before medicine confirmed the mind-body link, this proverb diagnosed it precisely: what lives in your heart writes itself into your bones.',
    meaning: '"A sound heart is the life of the flesh: but envy the rottenness of the bones" — a heart at peace gives health to the body; envy decays you from the inside, structurally, like rot in a beam. Envy always bills the one who hosts it.',
    you: 'The person you envy pays nothing for your envy — you pay everything. For your own health, physical and spiritual, evict it: name it, confess it, and thank God specifically for what is yours.',
    prayer: 'Lord, envy is rotting me from inside — I confess it and let it go. Give me a sound heart at peace with my portion. Amen.',
  },
  'Galatians 5:26': {
    story: 'Right after listing the fruit of the Spirit, Paul names the social diseases that kill community. His trio exposes how comparison wounds in both directions.',
    meaning: '"Let us not be desirous of vain glory, provoking one another, envying one another" — vain glory is empty applause-hunting; it makes you provoke those below you and envy those above you. Comparison poisons every relationship it touches.',
    you: 'Notice where comparison places people — above you (envy) or beneath you (contempt). The Spirit\'s alternative is neither: brothers and sisters beside you. Step out of the ranking game entirely.',
    prayer: 'Spirit of God, free me from the ladder — from craving glory, provoking, envying. Teach me to walk beside people. Amen.',
  },
  'James 3:16': {
    story: 'James contrasts two kinds of wisdom — one from above, one "earthly, sensual, devilish." The test is what each produces. Envy\'s harvest is described with unsettling precision.',
    meaning: '"For where envying and strife is, there is confusion and every evil work" — envy is never a private vice; it generates disorder around it — in homes, churches, teams. Find chronic chaos, and envy is often somewhere in the soil.',
    you: 'If confusion keeps following you, audit the root: is envy or rivalry underneath? Peace-filled wisdom from above is "first pure, then peaceable" — ask God for that instead.',
    prayer: 'Father, pull envy out of my soil before it grows confusion. Give me the pure, peaceable wisdom from above. Amen.',
  },
  'Philippians 4:11-12': {
    story: 'Thanking the Philippians for a gift, Paul clarifies something remarkable: his welfare no longer depends on circumstances. He names contentment for what it is — not a temperament, but a curriculum.',
    meaning: '"I have learned, in whatsoever state I am, therewith to be content... both to abound and to suffer need" — learned, through actual abundance and actual hunger. Contentment is acquired by walking with Christ through both extremes.',
    you: 'You keep waiting for contentment to arrive with better circumstances. It does not arrive — it is learned, right where you are, lesson by lesson. Today\'s situation is part of the coursework.',
    prayer: 'Lord, enrol me in Paul\'s school: teach me contentment in this exact state — plenty or need — through Christ. Amen.',
  },
  '1 Timothy 6:6-7': {
    story: 'Warning Timothy about teachers who treated godliness as a money-making angle, Paul flips the equation: the real fortune is not what godliness gets you — it is what godliness plus contentment already is.',
    meaning: '"Godliness with contentment is great gain. For we brought nothing into this world, and it is certain we can carry nothing out" — the entry and exit are both empty-handed; everything between is stewardship, not ownership. Contentment is wealth without inventory.',
    you: 'Envy audits other people\'s baggage on a trip where all luggage stays behind. Godliness with contentment — that combination is the only portfolio that survives the exit.',
    prayer: 'Lord, I came in with nothing and leave with nothing. Make godliness with contentment my great gain today. Amen.',
  },
  'Exodus 20:17': {
    story: 'The Ten Commandments end by moving from actions to appetites. Nine commandments govern what you do; the tenth walks into the heart and addresses what you want.',
    meaning: '"Thou shalt not covet thy neighbour\'s house... nor any thing that is thy neighbour\'s" — coveting is desire aimed at what God assigned to someone else. Its placement is a kindness: God bans the inner fire before it becomes theft, adultery, or murder.',
    you: 'This command is God protecting *you* — a coveting heart is a burning house. Guard the wanting, and the doing guards itself. Pray gratitude daily; it is coveting\'s natural predator.',
    prayer: 'Lord, You banned coveting to keep my heart from burning. Replace my wanting with thanks for what You assigned me. Amen.',
  },
  '1 Corinthians 13:4': {
    story: 'Corinth\'s believers were competing over gifts, status, and leaders. Paul interrupted the contest with a portrait of love — and one of its first features is what love refuses to feel about another\'s success.',
    meaning: '"Charity suffereth long, and is kind; charity envieth not" — love and envy cannot occupy the same heart toward the same person, because envy resents their good while love celebrates it. Growing in love automatically starves envy.',
    you: 'The antidote to envying someone is deliberately loving them: pray for their success, congratulate them sincerely, serve them. Love acted out re-trains the heart until the envy dies of hunger.',
    prayer: 'God of love, teach me to celebrate what You give others. Fill me with love that leaves envy no room. Amen.',
  },
  'Proverbs 23:17': {
    story: 'A father warns his son against the oldest optical illusion: sinners who seem to be winning. His counsel names both the trap and the substitute discipline.',
    meaning: '"Let not thine heart envy sinners: but be thou in the fear of the Lord all the day long" — envy of the wicked is corrected not by argument but by orientation: all-day reverence. The next verse gives the reason: "surely there is an end," and your expectation will not be cut off.',
    you: 'Their highlight reel is missing its final scene; yours is missing its reward scene. Stay in the fear of the Lord all day long — the endings vindicate the faithful.',
    prayer: 'Lord, when wrongdoers seem to win, anchor me in Your fear all day long. My expectation is with You — it will not be cut off. Amen.',
  },
  'Psalm 73:2-3': {
    story: 'Asaph, a temple worship leader, confesses publicly how close he came to quitting the faith — and names the exact trigger: he watched the wicked prosper, and envy nearly took his feet from under him.',
    meaning: '"My feet were almost gone; my steps had well nigh slipped. For I was envious at the foolish, when I saw the prosperity of the wicked" — envy is a footing hazard for believers, strong enough to nearly topple a worship leader. His cure came later: entering God\'s sanctuary and seeing their end.',
    you: 'If envy nearly toppled Asaph, do not be ashamed that it shakes you — but do what he did: take it into God\'s presence. Perspective returns in the sanctuary; footing follows perspective.',
    prayer: 'Lord, envy has been shaking my footing. I bring it into Your presence — restore my perspective and steady my steps. Amen.',
  },
};
