// Wayfind curation source. Each emotion -> [reference, reflection].
// Verse TEXT is NOT stored here; the build script resolves real KJV/WEB text
// from the bundled Bible JSON so nothing is ever fabricated.
// Reflections are original pastoral notes (plain-language, warm, 1-2 sentences).

const clusters = [
  { id: 'distress', label: 'When you are hurting' },
  { id: 'struggle', label: 'When something feels wrong' },
  { id: 'need',     label: 'When life is pressing hard' },
  { id: 'positive', label: 'When your heart is full' },
  { id: 'seeking',  label: 'When you are reaching for God' },
];

// id, label, cluster, icon (lucide name), blurb (short helper line)
const emotions = [
  // DISTRESS
  { id: 'sad', label: 'Sad', cluster: 'distress', icon: 'CloudRain', blurb: 'For a heavy, sorrowful heart' },
  { id: 'grief', label: 'Grieving', cluster: 'distress', icon: 'HeartCrack', blurb: 'When you have lost someone or something' },
  { id: 'lonely', label: 'Lonely', cluster: 'distress', icon: 'User', blurb: 'When you feel alone or unseen' },
  { id: 'depressed', label: 'Depressed', cluster: 'distress', icon: 'Cloud', blurb: 'When the darkness will not lift' },
  { id: 'afraid', label: 'Afraid', cluster: 'distress', icon: 'ShieldAlert', blurb: 'When fear has a grip on you' },
  { id: 'anxious', label: 'Anxious', cluster: 'distress', icon: 'Wind', blurb: 'Worried, restless, overthinking' },
  { id: 'overwhelmed', label: 'Overwhelmed', cluster: 'distress', icon: 'Waves', blurb: 'When it is all too much' },
  // STRUGGLE
  { id: 'angry', label: 'Angry', cluster: 'struggle', icon: 'Flame', blurb: 'Anger, bitterness, resentment' },
  { id: 'guilty', label: 'Guilty', cluster: 'struggle', icon: 'EyeOff', blurb: 'Weighed down by shame or regret' },
  { id: 'tempted', label: 'Tempted', cluster: 'struggle', icon: 'Swords', blurb: 'Struggling against sin' },
  { id: 'doubtful', label: 'Doubting', cluster: 'struggle', icon: 'HelpCircle', blurb: 'Questioning your faith' },
  { id: 'discouraged', label: 'Discouraged', cluster: 'struggle', icon: 'TrendingDown', blurb: 'Feeling like a failure' },
  { id: 'insecure', label: 'Insecure', cluster: 'struggle', icon: 'Frown', blurb: '"I am not enough"' },
  { id: 'jealous', label: 'Jealous', cluster: 'struggle', icon: 'Eye', blurb: 'Comparing, envying others' },
  { id: 'confused', label: 'Confused', cluster: 'struggle', icon: 'Compass', blurb: 'Lost, unsure what to do' },
  // NEED
  { id: 'hurting', label: 'In Pain', cluster: 'need', icon: 'Pill', blurb: 'Sick or needing healing' },
  { id: 'provision', label: 'In Need', cluster: 'need', icon: 'Wallet', blurb: 'Worried about money or provision' },
  { id: 'heartbroken', label: 'Heartbroken', cluster: 'need', icon: 'Droplets', blurb: 'Betrayed or wounded in love' },
  { id: 'wronged', label: 'Wronged', cluster: 'need', icon: 'Scale', blurb: 'Treated unjustly' },
  { id: 'deciding', label: 'Deciding', cluster: 'need', icon: 'Map', blurb: 'Facing a big decision' },
  { id: 'unsafe', label: 'Unsafe', cluster: 'need', icon: 'Shield', blurb: 'Needing protection' },
  // POSITIVE
  { id: 'joyful', label: 'Joyful', cluster: 'positive', icon: 'Sun', blurb: 'Happy, glad, delighted' },
  { id: 'grateful', label: 'Grateful', cluster: 'positive', icon: 'Gift', blurb: 'Thankful for God’s goodness' },
  { id: 'hopeful', label: 'Hopeful', cluster: 'positive', icon: 'Sunrise', blurb: 'Expectant, waiting on God' },
  { id: 'peaceful', label: 'Peaceful', cluster: 'positive', icon: 'Feather', blurb: 'At rest, calm, still' },
  { id: 'courageous', label: 'Courageous', cluster: 'positive', icon: 'Mountain', blurb: 'Bold and ready' },
  { id: 'loved', label: 'Loved', cluster: 'positive', icon: 'Heart', blurb: 'Knowing you are God’s' },
  { id: 'strong', label: 'Strong', cluster: 'positive', icon: 'Anchor', blurb: 'Persevering, won’t give up' },
  // SEEKING
  { id: 'purposeless', label: 'Searching', cluster: 'seeking', icon: 'Target', blurb: '"What is my life for?"' },
  { id: 'forgiven', label: 'Seeking Mercy', cluster: 'seeking', icon: 'Sparkles', blurb: 'Needing to know you are forgiven' },
  { id: 'forgiving', label: 'Letting Go', cluster: 'seeking', icon: 'HandHeart', blurb: 'Trying to forgive someone' },
  { id: 'prayerless', label: 'Learning to Pray', cluster: 'seeking', icon: 'MessageCircle', blurb: 'Wanting to talk to God' },
  { id: 'worshipful', label: 'Worshipful', cluster: 'seeking', icon: 'Music', blurb: 'Ready to praise' },
  { id: 'numb', label: 'Spiritually Dry', cluster: 'seeking', icon: 'Snowflake', blurb: 'When God feels distant' },
];

const curation = {
  sad: [
    ['Psalm 34:18', 'God is not far when your heart is shattered. He draws close to the brokenhearted — not away from them.'],
    ['Psalm 30:5', 'Your tears are real, but they are not the final word. A new morning — and new joy — is always coming.'],
    ['Psalm 147:3', 'God is a healer, not just of bodies but of broken hearts. He tends your wounds with care.'],
    ['Psalm 55:22', 'You were never meant to carry your grief alone. Place it in His hands and He will hold you up.'],
    ['John 11:35', 'The shortest verse in the Bible carries a deep truth — Jesus is moved by your pain. He weeps with you.'],
    ['Matthew 5:4', 'Jesus calls the mourning "blessed" — not because sorrow is good, but because comfort is coming.'],
    ['Psalm 42:11', 'Even when your soul feels cast down, you can still speak hope to it: God is worth waiting for.'],
    ['Revelation 21:4', 'A day is coming when God Himself wipes every tear away, and sorrow has no place left to live.'],
    ['2 Corinthians 1:3-4', 'God is the source of all comfort — and the comfort He gives you can one day flow through you to others.'],
    ['Psalm 56:8', 'God keeps count of your sorrows and stores your tears. Not one of them is wasted or unseen.'],
    ['Psalm 126:5', 'The tears you sow in this hard season are not the end of the story — a harvest of joy is promised.'],
    ['John 16:22', 'The grief you feel now is real, but Jesus promises a joy that no one will ever take from you.'],
    ['Isaiah 53:3', 'Jesus was "a man of sorrows, acquainted with grief." He understands exactly where you are.'],
  ],
  grief: [
    ['Psalm 23:4', 'Even in the valley of the shadow of death, you are not walking alone — the Shepherd is with you.'],
    ['John 11:25-26', 'Jesus is the resurrection and the life. Death is not the final goodbye for those who are His.'],
    ['Revelation 21:4', 'There is a future with no more death, no more crying, no more pain. God promises it Himself.'],
    ['1 Thessalonians 4:13-14', 'Christians grieve — but not as those without hope. Death is not the end for those in Christ.'],
    ['2 Corinthians 1:3-4', 'God is the Father of mercies and the God of all comfort, near to you in your mourning.'],
    ['Psalm 34:18', 'God draws especially near to the broken — your shattered heart is not too much for Him.'],
    ['Psalm 73:26', 'Even when everything in you fails, God remains your strength and your portion forever.'],
    ['John 14:1-3', 'Jesus has gone to prepare a place. Let this steady your troubled heart in the days of loss.'],
    ['Romans 8:38-39', 'Not even death can separate you — or those who died in Christ — from the love of God.'],
    ['Psalm 116:15', 'The death of God’s people is precious in His sight. Your loved one is not forgotten by Him.'],
    ['Isaiah 25:8', 'God will swallow up death forever and wipe the tears from all faces. Grief has an expiry date.'],
    ['Lamentations 3:31-32', 'God does not cast off forever; though He allows grief, He shows compassion in great measure.'],
    ['Matthew 5:4', 'Blessed are those who mourn, for they shall be comforted — a promise straight from Jesus.'],
  ],
  lonely: [
    ['Deuteronomy 31:6', 'However abandoned you feel, God has promised He will not leave you. Not now, not ever.'],
    ['Hebrews 13:5', 'A direct promise from God to you: "I will never leave thee, nor forsake thee."'],
    ['Psalm 68:6', 'God sees those who are alone and works to bring them into belonging. Isolation is not your home.'],
    ['Psalm 25:16', 'Even David cried out in loneliness. God welcomes this honest prayer — you can pray it too.'],
    ['Matthew 28:20', 'Jesus’ last promise before ascending: "I am with you always." Always includes right now.'],
    ['Psalm 139:7-10', 'There is nowhere you can go from God’s presence. Even in the dark, His hand holds you.'],
    ['Psalm 27:10', 'Even if those closest to you forsake you, the Lord Himself will take you up.'],
    ['John 14:18', 'Jesus says, "I will not leave you comfortless." He does not abandon His own as orphans.'],
    ['Isaiah 41:10', 'You need not fear, for God is with you; He strengthens, helps, and upholds you.'],
    ['Psalm 73:23', 'Whatever you feel, the truth holds: you are continually with Him, and He holds your right hand.'],
    ['Joshua 1:9', 'Be strong and courageous — the Lord your God is with you wherever you go.'],
    ['Romans 8:38-39', 'Nothing in all creation can separate you from the love of God in Christ Jesus.'],
  ],
  depressed: [
    ['Psalm 42:11', 'When your soul is cast down, preach to it: hope in God, for you will yet praise Him.'],
    ['Psalm 34:17', 'When the righteous cry out, the Lord hears and delivers them out of all their troubles.'],
    ['Psalm 40:1-2', 'God lifts us out of the pit and the miry clay, and sets our feet upon a rock.'],
    ['1 Kings 19:7-8', 'When Elijah was so low he wanted to die, God did not scold him — He fed him and let him rest.'],
    ['Isaiah 40:31', 'Those who wait on the Lord renew their strength; they will rise again, even when worn down.'],
    ['Lamentations 3:22-23', 'His mercies are new every morning — today has a fresh supply you have not used up.'],
    ['Matthew 11:28', 'Jesus invites the weary and heavy-laden to come to Him for rest. That includes you, today.'],
    ['Psalm 3:3', 'The Lord is a shield around you and the One who lifts up your head when you cannot lift it yourself.'],
    ['2 Corinthians 4:8-9', 'Pressed but not crushed, struck down but not destroyed — this can be true of you too.'],
    ['Psalm 27:13-14', 'Wait on the Lord and take courage — you will see His goodness in the land of the living.'],
    ['John 16:33', 'In the world you will have trouble, but take heart: Jesus has overcome the world.'],
    ['Psalm 143:7-8', 'An honest prayer for the low days: "Cause me to hear thy lovingkindness in the morning."'],
    ['Psalm 147:3', 'He heals the brokenhearted and binds up their wounds — gently, and over time.'],
  ],
  afraid: [
    ['Isaiah 41:10', 'Five promises in one verse: I am with you, I am your God, I will strengthen, help, and uphold you.'],
    ['Psalm 27:1', 'When God is your light and your strength, fear loses its grip — whom shall you fear?'],
    ['2 Timothy 1:7', 'Fear is not from God. He has given you power, love, and a sound mind instead.'],
    ['Psalm 56:3', 'One of the most honest prayers: "What time I am afraid, I will trust in thee."'],
    ['1 John 4:18', 'God’s perfect love casts out fear. When you receive it fully, fear has no room to live.'],
    ['Joshua 1:9', 'Be strong and of good courage; do not be afraid, for the Lord is with you wherever you go.'],
    ['Psalm 23:4', 'Even in the darkest valley you need fear no evil, for the Shepherd is with you.'],
    ['Psalm 34:4', 'David sought the Lord, and He delivered him from all his fears. Seek Him with your fear too.'],
    ['Isaiah 43:1-2', 'When you pass through the waters and the fire, God says: I am with you, you are mine.'],
    ['Psalm 91:1-2', 'Those who dwell in the shelter of the Most High rest in the shadow of the Almighty.'],
    ['Proverbs 3:25-26', 'You need not be afraid of sudden trouble, for the Lord will be your confidence.'],
    ['Psalm 118:6', 'The Lord is on your side; you do not need to fear what people can do to you.'],
    ['Isaiah 41:13', 'God holds your right hand and says to you, "Fear not; I will help you."'],
  ],
  anxious: [
    ['Philippians 4:6-7', 'Be anxious for nothing; bring it all to God in prayer, and His peace will guard your heart.'],
    ['1 Peter 5:7', 'God is not burdened by your worries — He cares for you. Cast all of it on Him.'],
    ['Matthew 6:25-26', 'If God feeds the birds, He will care for you. You are far more valuable to Him.'],
    ['Matthew 6:34', 'Do not carry tomorrow’s weight today. Each day has enough — stay with what is in front of you.'],
    ['Psalm 55:22', 'Cast your burden on the Lord, and He will sustain you. He will not let you be shaken.'],
    ['John 14:27', 'Jesus gives a peace the world cannot — let it quiet your troubled, anxious heart.'],
    ['Isaiah 26:3', 'God keeps in perfect peace the mind that is fixed on Him. Where your mind rests matters.'],
    ['Psalm 94:19', 'When anxious thoughts multiply within you, God’s comfort delights your soul.'],
    ['Matthew 11:28-29', 'Come to Jesus, take His gentle yoke, and you will find rest for your weary, racing mind.'],
    ['Proverbs 12:25', 'Anxiety weighs the heart down, but a good word makes it glad. Let Scripture be that word.'],
    ['Psalm 46:1-2', 'God is your refuge and strength; you need not fear even when everything feels shaky.'],
    ['Colossians 3:15', 'Let the peace of God rule — act as the umpire — in your heart.'],
  ],
  overwhelmed: [
    ['Psalm 61:2', 'David did not pretend to be strong. When overwhelmed, he cried out for a higher rock — so can you.'],
    ['2 Corinthians 12:9', 'God’s grace is sufficient; His strength is made perfect in your weakness, not your strength.'],
    ['Philippians 4:13', 'Whatever God calls you to face, He gives the strength for it through Christ.'],
    ['Psalm 46:1', 'God is a very present help in trouble — a refuge you can run to right now.'],
    ['Matthew 11:28', 'Come to Jesus, all who labour and are heavy laden, and He will give you rest.'],
    ['Matthew 6:34', 'Do not carry tomorrow’s burden today; sufficient for the day is its own trouble.'],
    ['Isaiah 43:2', 'When you pass through deep waters, they will not overflow you — God is with you in them.'],
    ['Psalm 142:3', 'Even when your spirit is overwhelmed within you, God knows your path. You are not lost to Him.'],
    ['Psalm 121:1-2', 'Lift your eyes up; your help comes from the Lord, the Maker of heaven and earth.'],
    ['Isaiah 40:29', 'He gives power to the faint, and to those with no might He increases strength.'],
    ['Deuteronomy 33:27', 'The eternal God is your refuge, and underneath are the everlasting arms.'],
    ['Psalm 55:22', 'Cast your burden on the Lord; He will sustain you and never let the righteous be moved.'],
  ],
  angry: [
    ['Ephesians 4:26', 'Anger itself is not sin — but bring it to God before the day ends; do not let it fester.'],
    ['Proverbs 15:1', 'A soft answer turns away wrath. Gentleness can defuse what harsh words would ignite.'],
    ['Psalm 37:8', 'Holding onto anger mostly hurts you. Let it go, and let God handle what is unjust.'],
    ['Romans 12:19', 'When deeply wronged, release the need to repay. God says, "Vengeance is mine; I will repay."'],
    ['Proverbs 16:32', 'Mastering your anger is a greater victory than taking a city. Self-control is strength.'],
    ['James 1:19-20', 'Be quick to hear, slow to speak, slow to anger; human anger does not produce God’s righteousness.'],
    ['Ecclesiastes 7:9', 'Do not be quick in spirit to be angry, for anger rests in the heart of fools.'],
    ['Proverbs 14:29', 'The patient have great understanding, but the quick-tempered display their folly.'],
    ['Colossians 3:8', 'Put away anger, wrath, and malice — lay them down like a heavy coat you no longer need.'],
    ['Proverbs 19:11', 'Good sense makes one slow to anger, and it is to your glory to overlook an offense.'],
    ['Ephesians 4:31-32', 'Put away bitterness, and instead be kind and forgiving, as God in Christ forgave you.'],
    ['Psalm 4:4', 'Be angry, and do not sin; ponder it on your bed, and be still before God.'],
  ],
  guilty: [
    ['1 John 1:9', 'Bring your sin to God honestly, and He is faithful and just to forgive and cleanse you completely.'],
    ['Romans 8:1', 'If you are in Christ, the verdict is already in: there is now no condemnation. None.'],
    ['Psalm 103:12', 'As far as the east is from the west — that is how completely God removes your sin from you.'],
    ['Isaiah 1:18', 'God invites you to reason together; though your sins be as scarlet, they shall be white as snow.'],
    ['Romans 3:23-24', 'All have fallen short — and all can be justified freely by His grace through Christ.'],
    ['Psalm 32:5', 'When David confessed and stopped hiding, God forgave the guilt of his sin. So He will for you.'],
    ['Psalm 51:10', 'You can pray David’s prayer: "Create in me a clean heart, O God; renew a right spirit within me."'],
    ['Hebrews 8:12', 'God says He will be merciful to your wrongs and remember your sins no more.'],
    ['Micah 7:19', 'He will cast all your sins into the depths of the sea — not the shallows where they wash back.'],
    ['2 Corinthians 5:17', 'In Christ you are a new creation; the old has passed away, and the new has come.'],
    ['Isaiah 43:25', 'God blots out your transgressions for His own sake, and remembers your sins no more.'],
    ['1 John 2:1', 'If you do sin, you have an Advocate with the Father, Jesus Christ the righteous.'],
  ],
  tempted: [
    ['1 Corinthians 10:13', 'No temptation is beyond what you can bear — God always provides a way of escape.'],
    ['James 1:12', 'Blessed is the one who endures temptation; having stood the test, they receive the crown of life.'],
    ['Hebrews 2:18', 'Because Jesus Himself was tempted, He is able to help you when you are being tempted.'],
    ['Hebrews 4:15-16', 'Your High Priest understands temptation; come boldly to His throne to find grace to help.'],
    ['James 4:7', 'Submit to God, resist the devil, and he will flee from you. You are not powerless.'],
    ['Matthew 26:41', 'Watch and pray, so you do not fall — the spirit is willing, but the flesh is weak.'],
    ['Psalm 119:11', 'Hiding God’s word in your heart is a guard against sin in the moment of pressure.'],
    ['1 Peter 5:8-9', 'Be sober and watchful; resist the enemy, firm in faith — you are not the only one in this fight.'],
    ['Galatians 5:16', 'Walk by the Spirit, and you will not gratify the desires of the flesh.'],
    ['2 Peter 2:9', 'The Lord knows how to deliver the godly out of temptation. He has not left you to manage alone.'],
    ['Romans 6:14', 'Sin shall not be your master, for you are not under law but under grace.'],
    ['2 Timothy 2:22', 'Flee the desires of youth, and pursue righteousness, faith, love, and peace instead.'],
  ],
  doubtful: [
    ['Mark 9:24', 'The honest prayer of a struggling father: "Lord, I believe; help thou mine unbelief." God hears it.'],
    ['James 1:6', 'Ask in faith — but the very fact that you are asking shows your faith is not gone.'],
    ['John 20:27-29', 'Jesus met doubting Thomas with patience, not rebuke. He meets your honest doubt the same way.'],
    ['Hebrews 11:1', 'Faith is the substance of things hoped for, the evidence of things not seen — not the absence of questions.'],
    ['Isaiah 55:8-9', 'God’s thoughts and ways are higher than yours; not understanding everything is to be expected.'],
    ['Proverbs 3:5-6', 'Trust in the Lord with all your heart; lean not on your own understanding, and He will direct you.'],
    ['Jude 1:22', 'God’s people are told to be merciful to those who doubt — your doubt does not disqualify you.'],
    ['Romans 10:17', 'Faith comes by hearing, and hearing by the word of God. Feed your faith on Scripture.'],
    ['Psalm 77:11-12', 'When doubt rises, remember God’s past faithfulness; recall His works and meditate on them.'],
    ['Habakkuk 3:17-18', 'Even when nothing visibly works out, you can still choose to rejoice in the God of your salvation.'],
    ['Mark 11:24', 'Whatever you ask in prayer, believe that you receive it — faith grows as you practice it.'],
  ],
  discouraged: [
    ['Joshua 1:9', 'Be strong and courageous; do not be discouraged, for the Lord your God is with you everywhere.'],
    ['Isaiah 40:31', 'Those who wait on the Lord renew their strength and rise up with wings like eagles.'],
    ['Galatians 6:9', 'Do not grow weary in doing good; in due season you will reap, if you do not give up.'],
    ['Philippians 4:13', 'You can do all things through Christ who strengthens you — even this hard, draining thing.'],
    ['Psalm 27:13-14', 'Take heart and wait on the Lord; you will yet see His goodness in the land of the living.'],
    ['Deuteronomy 31:8', 'The Lord goes before you and will be with you; do not fear or be dismayed.'],
    ['2 Corinthians 4:16-18', 'Do not lose heart; though the outer self wastes away, the inner self is renewed day by day.'],
    ['Isaiah 41:10', 'Fear not, for God is with you; He will strengthen and help you and hold you up.'],
    ['1 Corinthians 15:58', 'Be steadfast; your labour in the Lord is not in vain, even when it feels fruitless.'],
    ['Nehemiah 8:10', 'The joy of the Lord is your strength — a source of power that does not depend on results.'],
    ['Psalm 31:24', 'Be of good courage, and He will strengthen your heart, all you who hope in the Lord.'],
    ['Hebrews 12:1-2', 'Run your race with endurance, looking to Jesus, the author and finisher of your faith.'],
  ],
  insecure: [
    ['Psalm 139:14', 'You are fearfully and wonderfully made. Your worth was settled by your Maker, not your critics.'],
    ['Isaiah 43:1-4', 'God says you are precious in His eyes, honored, and loved. He calls you by name.'],
    ['Ephesians 2:10', 'You are God’s workmanship, created for good works He prepared beforehand for you to do.'],
    ['Jeremiah 1:5', 'Before you were formed, God knew you. Your identity began in His mind, not in others’ opinions.'],
    ['1 Peter 2:9', 'You are chosen, royal, holy, God’s own — called out of darkness into His marvelous light.'],
    ['Romans 8:31', 'If God is for you, who can be against you? His verdict outweighs every other voice.'],
    ['Zephaniah 3:17', 'God rejoices over you with gladness and quiets you with His love. He delights in you.'],
    ['Galatians 2:20', 'Your life is now Christ living in you — you are defined by Him, not by your failures.'],
    ['2 Corinthians 12:9', 'His grace is enough for you; His power is perfected in your weakness, not your perfection.'],
    ['Matthew 10:29-31', 'God knows the number of hairs on your head. You are worth more than many sparrows to Him.'],
    ['Colossians 2:10', 'In Christ you are complete — not lacking, not less-than, but filled with His fullness.'],
    ['Genesis 1:27', 'You bear the image of God Himself. That is the dignity stamped on you from the beginning.'],
  ],
  jealous: [
    ['Psalm 37:1-4', 'Do not fret over those who prosper; delight in the Lord, and He gives you the desires of your heart.'],
    ['Proverbs 14:30', 'A peaceful heart gives life to the body, but envy rots the bones. Envy costs you, not them.'],
    ['Galatians 5:26', 'Do not become conceited, provoking and envying one another — comparison only breeds strife.'],
    ['James 3:16', 'Where there is envy and selfish ambition, there is disorder. Peace grows in the opposite soil.'],
    ['Philippians 4:11-12', 'Paul learned contentment in any situation — it is a skill that can be learned, not a feeling you wait for.'],
    ['1 Timothy 6:6-7', 'Godliness with contentment is great gain; we brought nothing in and can take nothing out.'],
    ['Hebrews 13:5', 'Be content with what you have, for God has said He will never leave you.'],
    ['Exodus 20:17', 'The command not to covet is also a kindness — it frees you from always wanting another’s life.'],
    ['1 Corinthians 13:4', 'Love does not envy. As love grows in you, the grip of jealousy loosens.'],
    ['Proverbs 23:17', 'Do not let your heart envy sinners, but continue in the fear of the Lord all day long.'],
    ['Psalm 73:2-3', 'Even Asaph nearly stumbled with envy at the prosperous — you are not alone in this struggle.'],
  ],
  confused: [
    ['Proverbs 3:5-6', 'When you cannot see the path, trust the One who can; acknowledge Him, and He will direct your steps.'],
    ['James 1:5', 'If you lack wisdom, ask God, who gives generously to all without finding fault.'],
    ['1 Corinthians 14:33', 'God is not the author of confusion but of peace. You can ask Him to bring clarity.'],
    ['Psalm 119:105', 'God’s word is a lamp to your feet — it shows the next step, which is enough for now.'],
    ['Psalm 32:8', 'God promises to instruct you and teach you the way you should go, with His eye upon you.'],
    ['Isaiah 30:21', 'You will hear a voice behind you saying, "This is the way; walk in it," when you turn aside.'],
    ['Jeremiah 33:3', 'Call to God, and He will answer and show you great and hidden things you do not know.'],
    ['Isaiah 55:8-9', 'God’s ways are higher than yours; you do not need to understand it all to follow Him.'],
    ['Psalm 37:23', 'The steps of a good person are ordered by the Lord, even when the way feels unclear.'],
    ['Romans 8:28', 'God works all things — even the confusing ones — together for good to those who love Him.'],
    ['Proverbs 16:9', 'A person plans their way, but the Lord directs their steps. You can trust His leading.'],
  ],
  hurting: [
    ['Psalm 34:19', 'Many are the afflictions of the righteous, but the Lord delivers them out of them all.'],
    ['Psalm 147:3', 'He heals the brokenhearted and binds up their wounds — body and soul alike.'],
    ['Isaiah 53:5', 'By His wounds we are healed. Jesus bore your suffering so you would not bear it alone.'],
    ['James 5:14-15', 'Call on others to pray over you; the prayer of faith does real work in real bodies.'],
    ['Jeremiah 17:14', 'A simple, honest prayer: "Heal me, O Lord, and I shall be healed; save me, and I shall be saved."'],
    ['Psalm 103:2-3', 'Bless the Lord, who forgives all your sin and heals all your diseases. Forget not His benefits.'],
    ['Psalm 30:2', 'David cried to the Lord for help, and God healed him. Bring your pain to Him directly.'],
    ['Matthew 11:28', 'Come to Jesus, all who are weary and burdened with pain, and He will give you rest.'],
    ['2 Corinthians 12:9', 'When healing tarries, His grace is still sufficient, and His strength meets your weakness.'],
    ['Psalm 41:3', 'The Lord sustains and strengthens those on a bed of illness. He has not forgotten you.'],
    ['1 Peter 2:24', 'He bore our sins in His body on the tree — by His stripes you were healed.'],
    ['Revelation 21:4', 'A day is coming with no more pain; the former things will all have passed away.'],
  ],
  provision: [
    ['Philippians 4:19', 'God will supply all your needs according to His riches in glory by Christ Jesus.'],
    ['Matthew 6:31-33', 'Do not be anxious about food or clothing; seek first His kingdom, and these will be added to you.'],
    ['Psalm 23:1', 'The Lord is your shepherd; with Him as your provider, you shall not be in want.'],
    ['Matthew 6:26', 'God feeds the birds, who do not store up barns. You are worth far more to Him than they.'],
    ['Psalm 37:25', 'David testified he had never seen the righteous forsaken or their children begging bread.'],
    ['Luke 12:24', 'Consider the ravens: God feeds them. How much more valuable are you than the birds!'],
    ['Proverbs 3:9-10', 'Honor the Lord with what you have, and your needs will not be the end of the story.'],
    ['Malachi 3:10', 'God invites you to test His faithfulness in giving — to see if He will not pour out blessing.'],
    ['2 Corinthians 9:8', 'God is able to make all grace abound to you, so that you have all you need for every good work.'],
    ['Psalm 34:10', 'Those who seek the Lord shall not lack any good thing, even when others go hungry.'],
    ['Matthew 7:11', 'If imperfect parents give good gifts, how much more will your Father in heaven give to you?'],
    ['Psalm 84:11', 'The Lord gives grace and glory; no good thing does He withhold from those who walk uprightly.'],
  ],
  heartbroken: [
    ['Psalm 34:18', 'The Lord is near to the brokenhearted and saves the crushed in spirit. He is close right now.'],
    ['Psalm 147:3', 'He heals the brokenhearted and binds up their wounds with tenderness.'],
    ['Psalm 55:22', 'Cast this heavy burden on the Lord, and He will sustain you through the ache.'],
    ['John 14:1', 'Let not your heart be troubled — believe in God, and believe also in Jesus.'],
    ['Psalm 27:10', 'Even if those you love forsake you, the Lord will take you up and hold you close.'],
    ['Isaiah 61:1', 'Jesus came to bind up the brokenhearted and to bring good news to the hurting.'],
    ['Psalm 73:26', 'Though your heart and flesh fail, God is the strength of your heart and your portion forever.'],
    ['Matthew 11:28-29', 'Come to Jesus with your weary, wounded heart, and you will find rest for your soul.'],
    ['Romans 8:28', 'God can weave even this heartbreak into something good for those who love Him.'],
    ['Psalm 30:5', 'Weeping may stay for the night, but joy comes in the morning. This night will not last forever.'],
    ['1 Peter 5:7', 'Cast all your anxiety and pain on Him, because He genuinely cares for you.'],
    ['Psalm 51:17', 'A broken and contrite heart God will not despise — He receives it tenderly.'],
  ],
  wronged: [
    ['Romans 12:19', 'Do not avenge yourselves; leave room for God’s justice, for vengeance belongs to Him.'],
    ['1 Peter 2:23', 'When reviled, Jesus did not retaliate but entrusted Himself to God who judges justly. So can you.'],
    ['Matthew 5:44', 'Love your enemies and pray for those who mistreat you — a hard freedom that breaks the cycle.'],
    ['Romans 12:17-18', 'Repay no one evil for evil; as far as it depends on you, live peaceably with all.'],
    ['Proverbs 20:22', 'Do not say, "I will repay evil"; wait for the Lord, and He will deliver you.'],
    ['1 Peter 3:9', 'Do not return evil for evil, but bless — for to this you were called, that you may inherit a blessing.'],
    ['Psalm 34:17', 'When the righteous cry out, the Lord hears and delivers them from all their troubles.'],
    ['Isaiah 54:17', 'No weapon formed against you shall prosper — this is the heritage of the servants of the Lord.'],
    ['Genesis 50:20', 'What others meant for evil, God can mean for good, as He did for Joseph.'],
    ['Luke 6:27-28', 'Do good to those who hate you, and pray for those who abuse you — the path Jesus walked.'],
    ['Romans 12:21', 'Do not be overcome by evil, but overcome evil with good.'],
    ['Psalm 9:9', 'The Lord is a refuge for the oppressed, a stronghold in times of trouble.'],
  ],
  deciding: [
    ['Proverbs 3:5-6', 'Trust the Lord with all your heart, and in all your ways acknowledge Him; He will direct your paths.'],
    ['James 1:5', 'If you lack wisdom for this decision, ask God, who gives generously without reproach.'],
    ['Psalm 32:8', 'God promises to instruct you and counsel you with His eye upon you. You are not deciding alone.'],
    ['Proverbs 16:9', 'You make your plans, but the Lord directs your steps — you can move forward and trust Him with it.'],
    ['Isaiah 30:21', 'You will hear His voice guiding: "This is the way; walk in it."'],
    ['Jeremiah 29:11', 'God’s thoughts toward you are of peace and a future. He is invested in where you are going.'],
    ['Psalm 37:23', 'The steps of a good person are ordered by the Lord; He delights in their way.'],
    ['Proverbs 16:3', 'Commit your works to the Lord, and your plans will be established.'],
    ['Psalm 25:4-5', 'Ask God to show you His ways and teach you His paths — a prayer for any crossroads.'],
    ['Proverbs 11:14', 'In an abundance of wise counsel there is safety. Seek godly advice as you decide.'],
    ['John 16:13', 'The Spirit of truth will guide you into all truth. You have a Helper in this.'],
    ['Psalm 143:8', 'Pray: "Cause me to know the way I should walk, for I lift up my soul to you."'],
  ],
  unsafe: [
    ['Psalm 91:1-2', 'Those who dwell in the shelter of the Most High abide in the shadow of the Almighty.'],
    ['Psalm 121:7-8', 'The Lord will keep you from all evil; He keeps your going out and coming in, now and forever.'],
    ['Proverbs 18:10', 'The name of the Lord is a strong tower; the righteous run into it and are safe.'],
    ['Psalm 46:1', 'God is your refuge and strength, a very present help in trouble.'],
    ['Psalm 4:8', 'You can lie down and sleep in peace, for the Lord alone makes you dwell in safety.'],
    ['2 Thessalonians 3:3', 'The Lord is faithful; He will establish you and guard you against the evil one.'],
    ['Psalm 27:1', 'The Lord is your light and your salvation — whom shall you fear?'],
    ['Isaiah 41:10', 'Fear not, for God is with you; He will strengthen and uphold you with His right hand.'],
    ['Psalm 23:4', 'Even through the darkest valley you need fear no evil, for He is with you.'],
    ['Psalm 18:2', 'The Lord is your rock, your fortress, your deliverer, your shield, your stronghold.'],
    ['Nahum 1:7', 'The Lord is good, a stronghold in the day of trouble; He knows those who take refuge in Him.'],
    ['Psalm 56:3-4', 'When you are afraid, put your trust in God; what can mere flesh do to you?'],
  ],
  joyful: [
    ['Psalm 118:24', 'This is the day the Lord has made — rejoice and be glad in it. Joy can be a choice to see His goodness.'],
    ['Philippians 4:4', 'Paul wrote "rejoice always" from prison — this joy is rooted in who God is, not in circumstances.'],
    ['Nehemiah 8:10', 'The joy of the Lord is your strength — not just a feeling, but a source of power.'],
    ['Psalm 16:11', 'In God’s presence is fullness of joy, and pleasures forevermore at His right hand.'],
    ['Psalm 37:4', 'Delight yourself in the Lord, and He will give you the desires of your heart.'],
    ['John 15:11', 'Jesus shares His words so that His joy may be in you and your joy may be full.'],
    ['Psalm 126:3', 'The Lord has done great things for us, and we are glad.'],
    ['Romans 15:13', 'May the God of hope fill you with all joy and peace in believing.'],
    ['Galatians 5:22-23', 'Joy is fruit of the Spirit — it grows in you as you walk with Him.'],
    ['Psalm 28:7', 'The Lord is your strength and shield; your heart trusts Him, and you are helped and greatly rejoice.'],
    ['1 Peter 1:8', 'Though you have not seen Him, you love Him and rejoice with joy inexpressible and full of glory.'],
    ['Psalm 30:11', 'God can turn your mourning into dancing and clothe you with gladness.'],
  ],
  grateful: [
    ['1 Thessalonians 5:18', 'In everything give thanks — this is God’s will for you. Thankfulness changes how you see everything.'],
    ['Psalm 136:1', 'Give thanks to the Lord, for He is good; His mercy endures forever.'],
    ['Psalm 103:1-2', 'Bless the Lord, O my soul, and forget not all His benefits — gratitude is sometimes a discipline.'],
    ['James 1:17', 'Every good and perfect gift comes down from the Father; gratitude traces the gift back to the Giver.'],
    ['Psalm 100:4', 'Enter His gates with thanksgiving and His courts with praise — thankfulness is a doorway to His presence.'],
    ['Colossians 3:15-17', 'Let thankfulness fill your words and songs, doing everything in the name of the Lord Jesus.'],
    ['Psalm 107:1', 'Give thanks to the Lord, for He is good; His steadfast love endures forever.'],
    ['Philippians 4:6', 'Bring your requests to God with thanksgiving — gratitude and prayer belong together.'],
    ['2 Corinthians 9:15', 'Thanks be to God for His indescribable gift — Jesus, the gift beyond all words.'],
    ['Psalm 9:1', 'Give thanks with your whole heart, and tell of all His wonderful deeds.'],
    ['Ephesians 5:20', 'Give thanks always and for everything to God the Father in the name of our Lord Jesus.'],
    ['1 Chronicles 16:34', 'O give thanks to the Lord, for He is good; His love endures forever.'],
  ],
  hopeful: [
    ['Jeremiah 29:11', 'God is thinking good thoughts toward your future — plans for peace, to give you hope and an end you long for.'],
    ['Romans 15:13', 'May the God of hope fill you with joy and peace, so you abound in hope by the Spirit’s power.'],
    ['Isaiah 40:31', 'Those who wait on the Lord renew their strength and mount up with wings as eagles.'],
    ['Habakkuk 2:3', 'The vision is for an appointed time; though it tarry, wait for it — it will surely come.'],
    ['Romans 8:28', 'Not some things — all things — God works together for good to those who love Him.'],
    ['Lamentations 3:21-23', 'This I recall and have hope: His mercies are new every morning; great is His faithfulness.'],
    ['Romans 5:3-5', 'Suffering produces perseverance, character, and hope — and hope does not put us to shame.'],
    ['Hebrews 6:19', 'Hope is an anchor for the soul, firm and secure, reaching behind the veil to Christ Himself.'],
    ['Psalm 130:5', 'I wait for the Lord, my soul waits, and in His word I put my hope.'],
    ['Micah 7:7', 'As for me, I will look to the Lord; I will wait for the God of my salvation; my God will hear me.'],
    ['Proverbs 23:18', 'Surely there is a future, and your hope will not be cut off.'],
    ['Psalm 31:24', 'Be strong, and let your heart take courage, all you who hope in the Lord.'],
  ],
  peaceful: [
    ['Numbers 6:24-26', 'This ancient blessing is spoken over you today: the Lord bless you, keep you, and give you peace.'],
    ['Philippians 4:7', 'The peace of God, which surpasses understanding, will guard your heart and mind in Christ Jesus.'],
    ['Psalm 23:1-3', 'The Shepherd leads you to green pastures and still waters, and restores your soul.'],
    ['Psalm 116:7', 'Return to your rest, O my soul, for the Lord has dealt bountifully with you.'],
    ['Psalm 119:165', 'Great peace have those who love God’s law, and nothing makes them stumble.'],
    ['John 14:27', 'Jesus gives a peace unlike the world’s — deep calm that holds even in chaos.'],
    ['Isaiah 26:3', 'God keeps in perfect peace the one whose mind is fixed on Him, because they trust Him.'],
    ['Colossians 3:15', 'Let the peace of Christ rule in your heart, to which you were called as one body.'],
    ['Matthew 11:28-29', 'Take Jesus’ gentle yoke, and you will find rest for your soul.'],
    ['Psalm 4:8', 'In peace you can lie down and sleep, for the Lord alone makes you dwell in safety.'],
    ['John 16:33', 'In Christ you may have peace; in the world there is trouble, but He has overcome the world.'],
    ['Isaiah 32:17', 'The fruit of righteousness is peace, and its effect quietness and trust forever.'],
  ],
  courageous: [
    ['Joshua 1:9', 'Be strong and courageous; do not be afraid, for the Lord your God is with you wherever you go.'],
    ['Psalm 27:1', 'The Lord is your light and salvation and the strength of your life — whom shall you fear?'],
    ['Isaiah 41:10', 'Fear not, for God strengthens, helps, and upholds you with His righteous right hand.'],
    ['Deuteronomy 31:6', 'Be strong and of good courage; the Lord goes with you and will not fail or forsake you.'],
    ['1 Corinthians 16:13', 'Watch, stand firm in the faith, be courageous, be strong.'],
    ['2 Timothy 1:7', 'God gave you a spirit not of fear but of power, love, and a sound mind.'],
    ['Ephesians 6:10', 'Be strong in the Lord and in the strength of His might — the courage is His, given to you.'],
    ['Psalm 18:32-34', 'It is God who arms you with strength and makes your way secure, training your hands for the battle.'],
    ['Proverbs 28:1', 'The righteous are as bold as a lion — boldness flows from a clean conscience before God.'],
    ['1 Chronicles 28:20', 'Be strong and do the work; do not be afraid, for the Lord God is with you; He will not fail you.'],
    ['Psalm 138:3', 'On the day you called, God answered and emboldened you with strength in your soul.'],
    ['Joshua 1:7', 'Only be strong and very courageous, careful to walk in God’s word — and you will succeed.'],
  ],
  loved: [
    ['John 3:16', 'God so loved the world — you included — that He gave His only Son, that you might have eternal life.'],
    ['Romans 8:38-39', 'Nothing in all creation can separate you from the love of God in Christ Jesus.'],
    ['1 John 4:9-10', 'This is love: not that we loved God, but that He loved us and sent His Son for us.'],
    ['Jeremiah 31:3', 'God says, "I have loved you with an everlasting love; with lovingkindness I have drawn you."'],
    ['John 15:13', 'Greater love has no one than this — and Jesus laid down His life for you, His friend.'],
    ['Ephesians 3:17-19', 'May you grasp how wide, long, high, and deep the love of Christ is — a love beyond knowledge.'],
    ['Zephaniah 3:17', 'The Lord your God is in your midst; He will rejoice over you with singing and quiet you with His love.'],
    ['1 John 3:1', 'See what kind of love the Father has given, that you should be called a child of God — and you are.'],
    ['Romans 5:8', 'God shows His love in this: while we were still sinners, Christ died for us.'],
    ['Psalm 86:15', 'The Lord is merciful and gracious, slow to anger, abounding in steadfast love toward you.'],
    ['Isaiah 43:4', 'You are precious and honored in God’s eyes, and He loves you.'],
    ['Lamentations 3:22-23', 'His steadfast love never ceases; His mercies are new every morning.'],
  ],
  strong: [
    ['Isaiah 40:29-31', 'He gives power to the faint; those who wait on the Lord renew their strength and do not grow weary.'],
    ['Philippians 4:13', 'You can do all things through Christ who strengthens you.'],
    ['2 Corinthians 12:9-10', 'When you are weak, then you are strong, for His power rests on you in your weakness.'],
    ['Psalm 46:1', 'God is your refuge and strength, a very present help in trouble.'],
    ['Nehemiah 8:10', 'The joy of the Lord is your strength — it holds you up when your own resolve runs out.'],
    ['Ephesians 6:10', 'Be strong in the Lord and in the power of His might.'],
    ['Psalm 18:1-2', 'I love you, O Lord, my strength — my rock, my fortress, and my deliverer.'],
    ['Isaiah 41:10', 'God will strengthen you and help you and uphold you with His righteous right hand.'],
    ['Habakkuk 3:19', 'The Lord God is your strength; He makes your feet like the deer’s, able to tread the heights.'],
    ['Psalm 73:26', 'Though flesh and heart fail, God is the strength of your heart and your portion forever.'],
    ['1 Corinthians 15:58', 'Be steadfast, immovable, always abounding in the work of the Lord — your labour is not in vain.'],
    ['2 Timothy 4:7', '"I have fought the good fight, I have finished the race, I have kept the faith" — a finish line worth pressing toward.'],
  ],
  purposeless: [
    ['Jeremiah 29:11', 'God has plans for you — plans for peace and a future, not for harm. Your life has a direction in His hands.'],
    ['Ephesians 2:10', 'You are God’s handiwork, created in Christ for good works prepared in advance for you to walk in.'],
    ['Romans 8:28', 'God works all things together for good for those who love Him and are called to His purpose.'],
    ['Psalm 139:13-16', 'God formed you and wrote your days in His book before one of them came to be. You are not an accident.'],
    ['Proverbs 19:21', 'Many are the plans in a person’s heart, but the Lord’s purpose will stand.'],
    ['Philippians 1:6', 'He who began a good work in you will carry it to completion — your story is unfinished, not pointless.'],
    ['Colossians 3:23-24', 'Whatever you do, work at it with all your heart for the Lord — ordinary work gains eternal meaning.'],
    ['Esther 4:14', 'Perhaps you have come to your place "for such a time as this." Your position is not random.'],
    ['Psalm 138:8', 'The Lord will fulfill His purpose for you; His steadfast love endures forever.'],
    ['Isaiah 43:7', 'You were created for God’s glory — formed and made by Him for a reason.'],
    ['Romans 12:2', 'Be transformed by the renewing of your mind, so you can discern God’s good and perfect will.'],
  ],
  forgiven: [
    ['1 John 1:9', 'If you confess your sins, He is faithful and just to forgive you and cleanse you from all unrighteousness.'],
    ['Romans 8:1', 'There is now no condemnation for those who are in Christ Jesus. The case against you is closed.'],
    ['Psalm 103:12', 'As far as the east is from the west, so far has He removed your transgressions from you.'],
    ['Isaiah 43:25', 'God blots out your transgressions for His own sake and remembers your sins no more.'],
    ['Micah 7:18-19', 'God delights in mercy; He will tread your sins underfoot and cast them into the sea.'],
    ['Colossians 1:13-14', 'You have been rescued from darkness and brought into His kingdom, with redemption and forgiveness.'],
    ['Ephesians 1:7', 'In Christ you have redemption through His blood, the forgiveness of sins, according to His grace.'],
    ['Psalm 32:1', 'Blessed is the one whose transgression is forgiven, whose sin is covered.'],
    ['Hebrews 10:17', 'God says, "Their sins and lawless deeds I will remember no more." Forgiven means forgotten by Him.'],
    ['2 Corinthians 5:17', 'If anyone is in Christ, they are a new creation; the old has gone, the new has come.'],
    ['Acts 3:19', 'Repent and turn to God, that your sins may be blotted out and times of refreshing may come.'],
    ['Psalm 130:3-4', 'If God kept a record of sins, none could stand — but with Him there is forgiveness.'],
  ],
  forgiving: [
    ['Ephesians 4:31-32', 'Put away bitterness and be kind, forgiving one another as God in Christ forgave you.'],
    ['Colossians 3:13', 'Bear with one another and forgive, as the Lord has forgiven you.'],
    ['Matthew 6:14-15', 'If you forgive others, your heavenly Father will also forgive you.'],
    ['Matthew 18:21-22', 'Not seven times, but seventy times seven — forgiveness is meant to be a way of life, not a one-time act.'],
    ['Mark 11:25', 'When you stand praying, forgive, so your Father may forgive you.'],
    ['Luke 23:34', 'From the cross Jesus prayed, "Father, forgive them" — the hardest forgiveness, modeled for us.'],
    ['Luke 6:37', 'Do not judge, do not condemn, forgive — and you will be forgiven.'],
    ['Romans 12:19', 'Leave room for God’s justice; you can release the debt because He will settle every account.'],
    ['1 Peter 4:8', 'Above all, love one another earnestly, since love covers a multitude of sins.'],
    ['Proverbs 17:9', 'Whoever covers an offense seeks love, but whoever repeats a matter separates close friends.'],
    ['Matthew 5:44', 'Love your enemies and pray for those who persecute you — prayer often softens the heart that forgives.'],
    ['Genesis 50:20', 'Like Joseph, you can come to say: what was meant for evil, God meant for good.'],
  ],
  prayerless: [
    ['Philippians 4:6-7', 'Pray about everything; bring your requests with thanksgiving, and His peace will guard you.'],
    ['Matthew 6:6-8', 'Prayer is not performance; go to your Father in secret, who already knows what you need.'],
    ['Romans 8:26', 'When you do not know what to pray, the Spirit Himself intercedes for you with groans words cannot express.'],
    ['1 Thessalonians 5:16-18', 'Rejoice always, pray continually, give thanks — prayer can become the rhythm of your day.'],
    ['James 5:16', 'The earnest prayer of a righteous person has great power and effect.'],
    ['Matthew 7:7', 'Ask and it will be given; seek and you will find; knock and the door will be opened.'],
    ['Psalm 145:18', 'The Lord is near to all who call on Him, to all who call on Him in truth.'],
    ['Jeremiah 29:12', 'You will call on Him and come and pray to Him, and He will listen to you.'],
    ['Luke 11:9-10', 'Everyone who asks receives, and the one who seeks finds — keep coming to Him.'],
    ['Hebrews 4:16', 'Come boldly to the throne of grace, to receive mercy and find grace to help in time of need.'],
    ['John 15:7', 'If you abide in Christ and His words abide in you, ask what you wish, and it will be done.'],
    ['Psalm 62:8', 'Trust in Him at all times; pour out your heart before Him, for God is a refuge for us.'],
  ],
  worshipful: [
    ['Psalm 100:1-2', 'Make a joyful noise to the Lord; serve Him with gladness and come before Him with singing.'],
    ['Psalm 95:1-2', 'Come, let us sing to the Lord and shout joyfully to the Rock of our salvation.'],
    ['Psalm 150:6', 'Let everything that has breath praise the Lord. Praise the Lord!'],
    ['Psalm 34:1', 'I will bless the Lord at all times; His praise shall continually be in my mouth.'],
    ['Psalm 103:1', 'Bless the Lord, O my soul, and all that is within me, bless His holy name.'],
    ['John 4:24', 'God is spirit, and those who worship Him must worship in spirit and in truth.'],
    ['Psalm 96:1-2', 'Sing to the Lord a new song; sing to the Lord, all the earth; bless His name.'],
    ['Psalm 145:3', 'Great is the Lord and greatly to be praised; His greatness is unsearchable.'],
    ['Revelation 4:11', 'Worthy are You, our Lord and God, to receive glory and honor and power.'],
    ['Hebrews 13:15', 'Through Jesus, continually offer a sacrifice of praise — the fruit of lips that confess His name.'],
    ['Psalm 63:3-4', 'Because His lovingkindness is better than life, your lips will praise Him; you will bless Him while you live.'],
    ['Psalm 29:2', 'Give to the Lord the glory due His name; worship the Lord in the beauty of holiness.'],
  ],
  numb: [
    ['Psalm 42:1-2', 'As the deer pants for water, so your soul thirsts for God — even this longing is a sign of life.'],
    ['Psalm 13:1-2', 'The honest cry "How long, O Lord, will you forget me?" is in the Bible — God can handle your raw questions.'],
    ['Lamentations 3:22-23', 'Even when you feel nothing, His mercies are new every morning; His faithfulness does not depend on your feelings.'],
    ['Psalm 63:1', 'O God, you are my God; earnestly I seek you in a dry and weary land where there is no water.'],
    ['Isaiah 40:31', 'Those who wait on the Lord will renew their strength — the dry season is not the end.'],
    ['Psalm 51:10-12', 'Pray: "Restore to me the joy of your salvation" — it is God’s to give back.'],
    ['Hosea 6:1-3', 'Return to the Lord; as surely as the dawn, He will come to you like the spring rains.'],
    ['Psalm 143:6', 'Stretch out your hands to Him; let your soul thirst for Him like a parched land.'],
    ['Revelation 3:20', 'Jesus stands at the door and knocks; if you open even a little, He will come in.'],
    ['Psalm 73:26', 'Though your heart feels like stone, God remains the strength of your heart and your portion.'],
    ['Jeremiah 29:13', 'You will seek Him and find Him when you search for Him with all your heart.'],
    ['Psalm 30:11-12', 'God can turn mourning into dancing again — the numbness is not your forever.'],
  ],
};

module.exports = { clusters, emotions, curation };
