// AUTO-GENERATED by scripts/build-curation.cjs — do not edit by hand.
export interface Cluster { id: string; label: string; }
export interface EmotionMeta { id: string; label: string; cluster: string; icon: string; blurb: string; }

export const clusters: Cluster[] = [
  {
    "id": "distress",
    "label": "When you are hurting"
  },
  {
    "id": "struggle",
    "label": "When something feels wrong"
  },
  {
    "id": "need",
    "label": "When life is pressing hard"
  },
  {
    "id": "positive",
    "label": "When your heart is full"
  },
  {
    "id": "seeking",
    "label": "When you are reaching for God"
  }
];

export const emotions: EmotionMeta[] = [
  {
    "id": "sad",
    "label": "Sad",
    "cluster": "distress",
    "icon": "CloudRain",
    "blurb": "For a heavy, sorrowful heart"
  },
  {
    "id": "grief",
    "label": "Grieving",
    "cluster": "distress",
    "icon": "HeartCrack",
    "blurb": "When you have lost someone or something"
  },
  {
    "id": "lonely",
    "label": "Lonely",
    "cluster": "distress",
    "icon": "User",
    "blurb": "When you feel alone or unseen"
  },
  {
    "id": "depressed",
    "label": "Depressed",
    "cluster": "distress",
    "icon": "Cloud",
    "blurb": "When the darkness will not lift"
  },
  {
    "id": "afraid",
    "label": "Afraid",
    "cluster": "distress",
    "icon": "ShieldAlert",
    "blurb": "When fear has a grip on you"
  },
  {
    "id": "anxious",
    "label": "Anxious",
    "cluster": "distress",
    "icon": "Wind",
    "blurb": "Worried, restless, overthinking"
  },
  {
    "id": "overwhelmed",
    "label": "Overwhelmed",
    "cluster": "distress",
    "icon": "Waves",
    "blurb": "When it is all too much"
  },
  {
    "id": "angry",
    "label": "Angry",
    "cluster": "struggle",
    "icon": "Flame",
    "blurb": "Anger, bitterness, resentment"
  },
  {
    "id": "guilty",
    "label": "Guilty",
    "cluster": "struggle",
    "icon": "EyeOff",
    "blurb": "Weighed down by shame or regret"
  },
  {
    "id": "tempted",
    "label": "Tempted",
    "cluster": "struggle",
    "icon": "Swords",
    "blurb": "Struggling against sin"
  },
  {
    "id": "doubtful",
    "label": "Doubting",
    "cluster": "struggle",
    "icon": "HelpCircle",
    "blurb": "Questioning your faith"
  },
  {
    "id": "discouraged",
    "label": "Discouraged",
    "cluster": "struggle",
    "icon": "TrendingDown",
    "blurb": "Feeling like a failure"
  },
  {
    "id": "insecure",
    "label": "Insecure",
    "cluster": "struggle",
    "icon": "Frown",
    "blurb": "\"I am not enough\""
  },
  {
    "id": "jealous",
    "label": "Jealous",
    "cluster": "struggle",
    "icon": "Eye",
    "blurb": "Comparing, envying others"
  },
  {
    "id": "confused",
    "label": "Confused",
    "cluster": "struggle",
    "icon": "Compass",
    "blurb": "Lost, unsure what to do"
  },
  {
    "id": "hurting",
    "label": "In Pain",
    "cluster": "need",
    "icon": "Pill",
    "blurb": "Sick or needing healing"
  },
  {
    "id": "provision",
    "label": "In Need",
    "cluster": "need",
    "icon": "Wallet",
    "blurb": "Worried about money or provision"
  },
  {
    "id": "heartbroken",
    "label": "Heartbroken",
    "cluster": "need",
    "icon": "Droplets",
    "blurb": "Betrayed or wounded in love"
  },
  {
    "id": "wronged",
    "label": "Wronged",
    "cluster": "need",
    "icon": "Scale",
    "blurb": "Treated unjustly"
  },
  {
    "id": "deciding",
    "label": "Deciding",
    "cluster": "need",
    "icon": "Map",
    "blurb": "Facing a big decision"
  },
  {
    "id": "unsafe",
    "label": "Unsafe",
    "cluster": "need",
    "icon": "Shield",
    "blurb": "Needing protection"
  },
  {
    "id": "joyful",
    "label": "Joyful",
    "cluster": "positive",
    "icon": "Sun",
    "blurb": "Happy, glad, delighted"
  },
  {
    "id": "grateful",
    "label": "Grateful",
    "cluster": "positive",
    "icon": "Gift",
    "blurb": "Thankful for God’s goodness"
  },
  {
    "id": "hopeful",
    "label": "Hopeful",
    "cluster": "positive",
    "icon": "Sunrise",
    "blurb": "Expectant, waiting on God"
  },
  {
    "id": "peaceful",
    "label": "Peaceful",
    "cluster": "positive",
    "icon": "Feather",
    "blurb": "At rest, calm, still"
  },
  {
    "id": "courageous",
    "label": "Courageous",
    "cluster": "positive",
    "icon": "Mountain",
    "blurb": "Bold and ready"
  },
  {
    "id": "loved",
    "label": "Loved",
    "cluster": "positive",
    "icon": "Heart",
    "blurb": "Knowing you are God’s"
  },
  {
    "id": "strong",
    "label": "Strong",
    "cluster": "positive",
    "icon": "Anchor",
    "blurb": "Persevering, won’t give up"
  },
  {
    "id": "purposeless",
    "label": "Searching",
    "cluster": "seeking",
    "icon": "Target",
    "blurb": "\"What is my life for?\""
  },
  {
    "id": "forgiven",
    "label": "Seeking Mercy",
    "cluster": "seeking",
    "icon": "Sparkles",
    "blurb": "Needing to know you are forgiven"
  },
  {
    "id": "forgiving",
    "label": "Letting Go",
    "cluster": "seeking",
    "icon": "HandHeart",
    "blurb": "Trying to forgive someone"
  },
  {
    "id": "prayerless",
    "label": "Learning to Pray",
    "cluster": "seeking",
    "icon": "MessageCircle",
    "blurb": "Wanting to talk to God"
  },
  {
    "id": "worshipful",
    "label": "Worshipful",
    "cluster": "seeking",
    "icon": "Music",
    "blurb": "Ready to praise"
  },
  {
    "id": "numb",
    "label": "Spiritually Dry",
    "cluster": "seeking",
    "icon": "Snowflake",
    "blurb": "When God feels distant"
  }
];

export const emotionById: Record<string, EmotionMeta> = Object.fromEntries(emotions.map((e) => [e.id, e]));

export const emotionsByCluster: Record<string, EmotionMeta[]> = clusters.reduce((acc, c) => {
  acc[c.id] = emotions.filter((e) => e.cluster === c.id);
  return acc;
}, {} as Record<string, EmotionMeta[]>);
